### ISSUE TITLE
cstranslate parsing issue

### ISSUE THREAD

**Issue by DanBuchan** [soedinglab/hh-suite#10]
hhmake output hhm files that begin with a first line which reads
"HHSearch 1.5"

If you build ffdata, ffindex files for a library of hhms and then run cstranslate to build the cs219 files cstranslate throws and error that the hhm file is malfornated. This can be remedied by removing this first line from hhms prior to running ffindex_build but really this should be handled gracefully in cstranslate.

For now, prior to running ffindex_build I have been using this to remove the first line from a dir of hhms

for i in `ls`; do tail -n +2 $i > tmpfile; mv tmpfile $i;done

**Comment by milot-mirdita** [comment]
Hi Dan,
You can build cs219 with a3m (or prf, seq, fas, a2m or ca3m) as the source. Hhm are unsupported as input files.
What -I parameter did you give to cstranslate? It is a bit surprising that you are getting output at all.

**Comment by DanBuchan** [comment]
cstranslate -A /PATH/cs219.lib -D /PATH/context_data.lib -x 0.3 -c 4 -f -i scop70_1.75_a3m -o scop70_1.75_cs219 -I a3m -b
