### ISSUE TITLE
uniclust30_2018_08 error hhdatabase.cpp:35  FFindexDatabase ERROR: could not open file 'uniclust30_2018_08 / _cs219.ffdata'

### ISSUE THREAD

**Issue by alexandergz1983** [soedinglab/hh-suite#107]
regards

I have installed version 3.0 of hh-suite installed on an ubuntu server 16.04. I downloaded the uniclust30_2018_08 database, however when I run hhblits, I get the following error:

Executed command:

hhblits -i file.fasta -o output -n 1 -d uniclust30_2018_08

ERROR: In /home/alex/software/hh-suite/src/hhdatabase.cpp:35: FFindexDatabase:

ERROR: could not open file 'uniclust30_2018_08 / _cs219.ffdata'

Any ideas to solve this problem?

Thank you

**Comment by lucky295** [comment]
looks like your path is not correct. It should be below like this
 hhblits -i file.fasta -o output -n 1 -d uniclust30_2018_08/uniclust30_2018_08
