### ISSUE TITLE
Could not open file '/usr/share/hhsuite/data/context_data.crf

### ISSUE THREAD

**Issue by acpguedes** [soedinglab/hh-suite#108]
COMMAND: 
hhalign -i Lip4_esther.rawtable.selected.aln -t Dali_alignment_Lip4_edited.fa -id 80
ERROR:
- 17:04:54.609 INFO: Search results will be written to Lip4_esther.rawtable.selected.hhr!

- 17:04:54.609 ERROR: Could not open file '/usr/share/hhsuite/data/context_data.crf'

DATA:
Both, input and template are MSA in fasta formated (letters and dash).
 
- [x] included the HHsuite version or commit ID
HHblits 3.0.0 (15-03-2015)

**Comment by merkys** [comment]
Have you built hhsuite from the source or do you use prebuilt package (i.e. Ubuntu/Debian)?

**Comment by Lolasdasdasd** [comment]
I actually have the same problem. After I cloned the repository from git and installed everything (version 3.0.3), any call such as : path/hh-suite/bin/hhalign ... throws the error:
- 16:26:35.660 ERROR: Could not open file '/usr/lib/hhsuite/data/context_data.crf'
