### ISSUE TITLE
warning infor "WARNING: No sequence name preceding following line in PF11847.8"

### ISSUE THREAD

**Issue by RiversDong** [soedinglab/hh-suite#109]
To help us debugging your issue, please make sure you

- [ ] included the HHsuite version or commit ID
- [ ] added information about your operating system and compiler (if building from source)
- [ ] checked the [user-guide](https://github.com/soedinglab/hh-suite/blob/master/hhsuite-userguide.pdf) for available documentation
- [ ] ideally also included a minimal example for us to reproduce the issue

**Comment by milot-mirdita** [comment]
The database should be fixed and working now. Please download it again.
