### ISSUE TITLE
Cannot copy hhsuite-userguide.pdf

### ISSUE THREAD

**Issue by vinhbiochem** [soedinglab/hh-suite#115]
Hi @mauricirl and all,

Sorry I'm a bit confused. I'm currently having the trouble that you had a few years back. Where did you happen to write "$ INSTALL_BASE_DIR=/home/maurizio/hhsuite"? Was it in your .bashrc file?

_Originally posted by @vinhbiochem in https://github.com/soedinglab/hh-suite/issue_comments#issuecomment-455400971_

**Comment by mircare** [comment]
Hi vinhbiochem,

Yes, as well as the following 2 lines:
```
export HHLIB=${INSTALL_BASE_DIR}
export PATH=${PATH}:${INSTALL_BASE_DIR}/bin:${INSTALL_BASE_DIR}/scripts
```

**Comment by vinhbiochem** [comment]
Hi @mircare ,

Thank you for the fast reply! Was able to make everything work out. Forgive me if this information was readily available.
