### ISSUE TITLE
how to install hh-suite in macOS?

### ISSUE THREAD

**Issue by lixingguang** [soedinglab/hh-suite#118]
To help us debugging your issue, please make sure you

- [ ] included the HHsuite version or commit ID
- [ ] added information about your operating system and compiler (if building from source)
- [ ] checked the [user-guide](https://github.com/soedinglab/hh-suite/blob/master/hhsuite-userguide.pdf) for available documentation
- [ ] ideally also included a minimal example for us to reproduce the issue

**Comment by milot-mirdita** [comment]
Make sure to install the latest GCC compiler from Homebrew (https://brew.sh). The apple provided Clang does not provide OpenMP support and will therefor produce non-parallelized builds.

Then follow the normal build instructions except altering the call to cmake:
```
CC=gcc-8 CXX=g++-8 cmake ...
```

**Comment by lixingguang** [comment]
@milot-mirdita still can not know how to install it, can you write a pipeline for this, thanks. :)

**Comment by milot-mirdita** [comment]
Can you please post the call and output of your `cmake` and `make` calls?

**Comment by lixingguang** [comment]
@milot-mirdita could you please tell me how to call make and cmake, thanks.
