### ISSUE TITLE
problem with hhpred Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at

### ISSUE THREAD

**Issue by alexandergz1983** [soedinglab/hh-suite#119]
I installed hh-suite through mini-crossover, however when I'm configuring hhpred, I get the following error:

(py36) server@server:~$ hhpred.pl 
Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at /home/alex/.conda/envs/py36/bin/lib/modeller.pm line 840.
Compilation failed in require at /home/alex/.conda/envs/py36/bin/hhpred.pl line 56.
BEGIN failed--compilation aborted at /home/alex/.conda/envs/py36/bin/hhpred.pl line 56.

Any ideas on this?

To help us debugging your issue, please make sure you

- [ ] included the HHsuite version or commit ID
- [ ] added information about your operating system and compiler (if building from source)
- [ ] checked the [user-guide](https://github.com/soedinglab/hh-suite/blob/master/hhsuite-userguide.pdf) for available documentation
- [ ] ideally also included a minimal example for us to reproduce the issue

**Comment by milot-mirdita** [comment]
Please use the latest git version, the issue should be solved in 815edc75718d8435a30769a8db511286416513de.

**Comment by alexandergz1983** [comment]
thank you very much, solved.
