### ISSUE TITLE
Script to parse HHR output file

### ISSUE THREAD

**Issue by sean-bam** [soedinglab/hh-suite#120]
Hey all,
Is there any publicly available script to parse an HHR output file from HHblits? I can't seem to awk/sed my way through the output to get the top hit(s). I would appreciate it if someone could share their code. I'm using HHblits v 3.0.3.  Thanks in advance for any help.

**Comment by mircare** [comment]
Hi @sean-bam,
Not sure about that but HHblits offers several output options. For example, I usually use -opsi to get the significant matches in PSI-BLAST format. You can find more in the user guide https://github.com/soedinglab/hh-suite/blob/master/hhsuite-userguide.pdf.

**Comment by sean-bam** [comment]
Hey @mircare, thanks for the suggestion to use the _-opsi_ flag for the output. However, the psi-blast MSA output does not include the probability score, e-values, etc. for each significant hit. What I am looking for is a script that can parse the [HHR_output.txt](https://github.com/soedinglab/hh-suite/files/2895210/HHR_output.txt) to return each value in a separate column (column 1 = Number, Column 2 = Hit, Column 3 = Prob, Column 4 = E-value, etc...).

**Comment by milot-mirdita** [comment]
We have a (currently) undocumented output mode `-blasttab` that will produce alignment results in BLAST `-m 8` compatible format. This should be a lot easier to parse.

However this mode does not take the maximum E-value (`-e`) threshold into account and will report everything.

**Comment by sean-bam** [comment]
Hey @milot-mirdita, that is exactly what I was looking for, thanks!

**Comment by UriNeri** [comment]
Hi @milot-mirdita 
The `-blasttab ` output file has 12 columns but the doc notes 11 ( where's #7 ?)
```
1      2      3           4         5        6      8    9      10   11   12
'query target #match/tLen #mismatch #gapOpen qstart qend tstart tend eval score'
```
There are 12 columns in the file though.
Sorry if I'm missing something obvious !

**Comment by milot-mirdita** [comment]
You are right, whoops. Column 4 (alignment length) is missing in the description.

It's the same format as MMseqs2 convertalis (https://github.com/soedinglab/mmseqs2/wiki#custom-alignment-format-with-convertalis): 
[...] alignment result in a BLAST tabular result (comparable to -m 8 -outfmt 6) with 12 columns: (1,2) identifiers for query and target sequences/profiles, (3) sequence identity, (4) alignment length, (5) number of mismatches, (6) number of gap openings, (7-8, 9-10) domain start and end-position in query and in target, (11) E-value, and (12) bit score.

**Comment by jrjhealey** [comment]
Realise there are answers here already, but I found this thread recently and wanted to share the way I approached this in my own script:

https://github.com/jrjhealey/bioinfo-tools/blob/master/tabulateHHpred.py

Using the `pandas.read_fwf` method, you can parse the more verbose "table" format of HHsuite. As long as you define the relevant template or column widths you can generalise this for any file I think.
