### ISSUE TITLE
MPQ_Init: Needs at least one worker process.

### ISSUE THREAD

**Issue by sabyUWO** [soedinglab/hh-suite#122]
Is there any documentation for the usage of hhblits_mpi and hhblits_omp, the parameters to pass etc.
When I run : /home/saby2k13/hh-suite/build/bin/hhblits_mpi -np 4  -i ${index}/foo  -ohhm Q9KNV2.txt -d ${database} , I get error : MPQ_Init: Needs at least one worker process.

**Comment by milot-mirdita** [comment]
The `_mpi` binaries don’t replace the need to call them with `mpirun`. The call would be:

```
mpirun -np 4 hhblits_mpi ...
```
