### ISSUE TITLE
License update.

### ISSUE THREAD

**Issue by mengyao** [soedinglab/hh-suite#123]
Please update your license description in hhprefilter.h according to SSW Library's updates in ssw.c:
https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library/blob/master/src/ssw.c

 Many thanks,

Mengyao

**Comment by martin-steinegger** [comment]
I have added the BSD clause on top of the MIT license. Thank you for your great library and we are thankful to Michael Farrar for his amazing algorithm.

**Comment by mengyao** [comment]
Thanks a lot. :-)

Yours,

Mengyao
