### ISSUE TITLE
HHsearch uses wrong lengths

### ISSUE THREAD

**Issue by dvs** [soedinglab/hh-suite#124]
Hello,

I think I've found an annoying bug that makes HHsearch v.3.x barely usable.
The description below relates to the latest HH-Suite version (and possibly to all the v.3.x releases).

## Expected Behavior

HHsearch v.3.x should read correct database's entry lengths, as HHblits does by reading lengths from the *_cs219.ffindex file.

## Current Behavior

When PfamA database is searched with HHsearch this message is printed:

    WARNING: database contains sequences that exceeds maximum allowed size (maxres = 20001). Maxres can be increased with parameter -maxres.

It appears that HHsearch uses the pfam_hhm.ffindex second column as the HMM profile length. In case of PfamA v.32 it wrongly estimates  PF06317.11 entry as a the longest profile with 262602 match states. But 262602 is the size of PF06317.11.hhm file, not the length of PF06317.11 profile. If user tries to resolve this issue by increasing the max. allowed size with -maxres option it then causes attempts of allocating very large memory chunks for the DP matrices search (AllocateBacktraceMatrix() is called for each used CPU core).
Otherwise, if this warning is ignored then most part of the PfamA is skipped because many of the HMM files collected in PfamA have size >20000 bytes.

In case of HHblits the same approach is correct because pfam_cs219.ffindex file indeed has entries with the length that corresponds to the profile length.

## Steps to Reproduce

    hhsearch -v 1 -i test.hhm -d pfam

**Comment by har-wradim** [comment]
$ hhsearch -h
	HHsearch 3.1.0

I experience similar symptoms: attempts to limit `maxres` with the pfamA_32.0 database lead to crashes with errors like: `free(): invalid next size (fast)` or `munmap_chunk(): invalid pointer`.

My ultimate goal is to run hhsearch against uniclust30 (yes, I know). With the default `maxres` it crashes once all of the available memory (62.5 GB) is exhausted, and limiting `maxres` leads to fatal errors like:

	- 10:35:52.153 ERROR: Uncharacterized protein OS=Bionectria ochroleuca OX=29856 GN=BN869_000013091_1 PE=4 SV=1 Split=0
	- 10:35:52.153 ERROR: Error in ~/src/hh-suite/src/hhalignment.cpp:1244: Compress:
	- 10:35:52.153 ERROR: 	sequences in 93158271 do not all have the same number of columns, 
	- 10:35:52.153 ERROR: 	
	e.g. first sequence and sequence tr|A0A0B7KHH9_0|A0A0B7KHH9_BIOOC.
	- 10:35:52.153 ERROR: Check input format for '-M a2m' option and consider using '-M first' or '-M 50'

**Comment by martin-steinegger** [comment]
This is indeed an annoying bug. HHsearch uses the real sequence length now by reading the `cs219` database. So it should take way less RAM to search. 
Now It is not possible to call HHsearch with a cs219 database. However, all our standard databases contains a `_cs219` database.

**Comment by dvs** [comment]
I confirm that this patch has fixed the bug. Thank you very much!

**Comment by Icco123** [comment]
Hi, when I use the following command:
"for i in `ls ./HHMs/`; do hhsearch -i ./HHMs/${i} -d ./msa/cluster1091 -id 100 -diff inf -M first -maxres 100000 -e 0.1 -loc -v 0 -Z 1000 -z 0 -B 10 -b 0 -p 10 -cpu 50 -o ./hhsearch_results/${i}.txt ; done ", 

when I run the above command this error occurs: "ERROR: sequences in ./HMMs/rep.AAM92745.1.IDs.mfa.hhm do not all have the same number of columns", I'm a little confused.

looking forward to your reply.

**Comment by lizongquan01** [comment]
> I confirm that this patch has fixed the bug. Thank you very much!

Which patch has fixed it？Would you please hint us, thanks a lot in advance!
