### ISSUE TITLE
inf] vs inf[

### ISSUE THREAD

**Issue by smsaladi** [soedinglab/hh-suite#127]
In the `-help` for various hh-suite programs, `inf` is used in two ways: `,inf]` and `,inf[`

Is there a distinction implied by one vs the other? 

for example:
> ```
> 
> Gap cost options:                                                                
>  -gapb [0,inf[  Transition pseudocount admixture (def=1.00)                     
>  -gapd [0,inf[  Transition pseudocount admixture for open gap (default=0.15)    
>  -gape [0,1.5]  Transition pseudocount admixture for extend gap (def=1.00)      
>  -gapf ]0,inf]  factor to increase/reduce gap open penalty for deletes (def=0.60) 
>  -gapg ]0,inf]  factor to increase/reduce gap open penalty for inserts (def=0.60) 
>  -gaph ]0,inf]  factor to increase/reduce gap extend penalty for deletes(def=0.60)
>  -gapi ]0,inf]  factor to increase/reduce gap extend penalty for inserts(def=0.60)
>  -egq  [0,inf[  penalty (bits) for end gaps aligned to query residues (def=0.00) 
>  -egt  [0,inf[  penalty (bits) for end gaps aligned to template residues (def=0.00)
> 
> ```

**Comment by martin-steinegger** [comment]
Its a indication for exclusion or inclusion of values: 
]0  <- must be larger than 0
[0 <- can be zero 
inf[ <- must be smaller than inf
inf]<- can be inf

**Comment by smsaladi** [comment]
Ah, I see ... I guess I've only encountered '(' vs '[' before, but this is nifty. Thanks for the clarification
