### ISSUE TITLE
Missing files after creating database

### ISSUE THREAD

**Issue by paulinefx** [soedinglab/hh-suite#13]
Hello,
I created a database with the chapter 3.5 of the userguide, but by the end I was missing files.
I only got : 
     <db>_a3m.ffdata
     <db>_a3m.ffinddex
     <db>_hhm.ffdata
     <db>_hhm.ffindex
     <db>_cs219.ffdata
     <db>_cs219.ffindex

I saw that the <db>_a3m_db, <db>_hhm_db were copies of the .ffdata and the <db>_a3m_db.index, <db>_hhm_db.index were copies of the .ffindex with the extensions of the file names. So they are easy to create with a script. But for the files <db>.cs219 and <db>.cs219.sizes I do not know how to create them.

For the creation of my database I already had alignments in fasta files, so I reformated them in a3m files, added the prediction of secondary structure, created the hhm files. Then I made the ffdat and ffindex for the a3m and hhm file. Then I used cstranslate to produce the cs219.ffdata and index, then I followed every step of the chapter 3.5.

Thank you in advance for your help.

Pauline

**Comment by milot-mirdita** [comment]
You only need those files if you want to use the database with the old legacy HH-suite 2.0.XX versions. If you are using the current HH-suite 3, you are already good to go. If you really need support for the old version, I can upload the scripts for you.

**Comment by paulinefx** [comment]
Ok ! I have the 2 versions on my computer and used the 2.0.16 version instead of the 3.
Thank you !

**Comment by milot-mirdita** [comment]
No problem, happy to help :)
