### ISSUE TITLE
[conda hhsuite] ERROR in FFindexDatabase

### ISSUE THREAD

**Issue by acpguedes** [soedinglab/hh-suite#130]
Hi, 

I installed HHSuite from conda, but seam I'm having some problems.

My environment are organized this way:
all databases needed in: `$ /databases/`
The conda is owned by user called `linuxbrew`, in its home has anaconda3 directory.

When installed HHSuite from anaconda I needed to set `HHLIB=/home/linuxbrew/anaconda3` because the HHSuite binaries are in `/home/linuxbrew/anaconda3/bin`, HHSuite scripts in `/home/linuxbrew/anaconda3/scripts` and HHSuite data in `/home/linuxbrew/anaconda3/data`.   
The PFAM and PDB70 are i `/databases/hhsuite`, them was downloaded from [here](http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs) and decompressed with `tar -xvzf`.

At this point `hhalign` runs. But when I try `hhblits -d /databases/hhsuite/pfam -i example.a3m` I got this error:
```
<pre>- 14:56:31.348 INFO: Search results will be written to Lip4_2.hhr

- 14:56:31.348 ERROR: In /opt/conda/conda-bld/hhsuite_1554456729008/work/src/ffindexdatabase.cpp:11: FFindexDatabase:

- 14:56:31.348 ERROR: 	could not open file &apos;/databases/hhsuite/pfam_cs219.ffdata&apos;
</pre>
```

Seams it are trying to open an inexistent file `/opt/conda/conda-bld/hhsuite_1554456729008/work/src/ffindexdatabase.cpp` at an inexistent directory `/opt/conda/conda-bld/hhsuite_1554456729008/work/src/` in a base directory completely different from those is was installed `/home/linuxbrew/anaconda3`.

How do you suggest I solve it??

Thanks in advance

**Comment by acpguedes** [comment]
Actually, I solved, I miss the permissions on files.

Now other issue pops out:

I have 32 cpu and 188GB of ram. But I'm getting a core dumping even if I control the `-cpu` and `-maxmem` parameter.

```
$ hhblits -d /databases/hhsuite/pdb70 -i Lip4_3.a3m -cpu 4 -maxmem 60

- 15:22:53.456 INFO: Search results will be written to Lip4_3.hhr

- 15:22:53.490 INFO: Searching 62713 column state sequences.

- 15:22:53.546 INFO: Lip4_3.a3m is in A2M, A3M or FASTA format

- 15:22:53.588 INFO: Iteration 1

- 15:22:53.732 INFO: Prefiltering database

- 15:22:54.108 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 2890

- 15:22:54.141 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 1028

- 15:22:54.141 INFO: HMMs passed 2nd prefilter and not found in previous iterations : 1028

- 15:22:54.141 INFO: Scoring 1028 HMMs using HMM-HMM Viterbi alignment

- 15:22:54.235 INFO: Alternative alignment: 0

- 15:22:54.664 INFO: 1028 alignments done

- 15:22:54.666 INFO: Alternative alignment: 1

- 15:22:55.018 INFO: 777 alignments done

- 15:22:55.019 INFO: Alternative alignment: 2

- 15:22:55.055 INFO: 34 alignments done

- 15:22:55.055 INFO: Alternative alignment: 3

- 15:22:55.059 INFO: 1 alignments done

- 15:22:55.103 INFO: Realigning 500 HMM-HMM alignments using Maximum Accuracy algorithm

Segmentation fault (core dumped)
```

**Comment by martin-steinegger** [comment]
Can you run the software without the `-maxmem 60` parameter?

**Comment by acpguedes** [comment]
Hi @martin-steinegger I did it, I ran default also tried to compile from GitHub and I had the same issue.

**Comment by acpguedes** [comment]
@martin-steinegger thanks for answer it, I did reinstall and configure again the environment, I don't know whats happens but now it is working. Thanks again.

**Comment by bluestreek2507** [comment]
> Actually, I solved, I miss the permissions on files.
> 
> Now other issue pops out:
> 
> I have 32 cpu and 188GB of ram. But I'm getting a core dumping even if I control the `-cpu` and `-maxmem` parameter.
> 
> ```
> $ hhblits -d /databases/hhsuite/pdb70 -i Lip4_3.a3m -cpu 4 -maxmem 60
> 
> - 15:22:53.456 INFO: Search results will be written to Lip4_3.hhr
> 
> - 15:22:53.490 INFO: Searching 62713 column state sequences.
> 
> - 15:22:53.546 INFO: Lip4_3.a3m is in A2M, A3M or FASTA format
> 
> - 15:22:53.588 INFO: Iteration 1
> 
> - 15:22:53.732 INFO: Prefiltering database
> 
> - 15:22:54.108 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 2890
> 
> - 15:22:54.141 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 1028
> 
> - 15:22:54.141 INFO: HMMs passed 2nd prefilter and not found in previous iterations : 1028
> 
> - 15:22:54.141 INFO: Scoring 1028 HMMs using HMM-HMM Viterbi alignment
> 
> - 15:22:54.235 INFO: Alternative alignment: 0
> 
> - 15:22:54.664 INFO: 1028 alignments done
> 
> - 15:22:54.666 INFO: Alternative alignment: 1
> 
> - 15:22:55.018 INFO: 777 alignments done
> 
> - 15:22:55.019 INFO: Alternative alignment: 2
> 
> - 15:22:55.055 INFO: 34 alignments done
> 
> - 15:22:55.055 INFO: Alternative alignment: 3
> 
> - 15:22:55.059 INFO: 1 alignments done
> 
> - 15:22:55.103 INFO: Realigning 500 HMM-HMM alignments using Maximum Accuracy algorithm
> 
> Segmentation fault (core dumped)
> ```

@acpguedes How did you solve this with the permissions? I am encountering the same problem....

thanks

**Comment by bluestreek2507** [comment]
> Hi,
> 
> I installed HHSuite from conda, but seam I'm having some problems.
> 
> My environment are organized this way:
> all databases needed in: `$ /databases/`
> The conda is owned by user called `linuxbrew`, in its home has anaconda3 directory.
> 
> When installed HHSuite from anaconda I needed to set `HHLIB=/home/linuxbrew/anaconda3` because the HHSuite binaries are in `/home/linuxbrew/anaconda3/bin`, HHSuite scripts in `/home/linuxbrew/anaconda3/scripts` and HHSuite data in `/home/linuxbrew/anaconda3/data`.
> The PFAM and PDB70 are i `/databases/hhsuite`, them was downloaded from [here](http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs) and decompressed with `tar -xvzf`.
> 
> At this point `hhalign` runs. But when I try `hhblits -d /databases/hhsuite/pfam -i example.a3m` I got this error:
> 
> ```
> <pre>- 14:56:31.348 INFO: Search results will be written to Lip4_2.hhr
> 
> - 14:56:31.348 ERROR: In /opt/conda/conda-bld/hhsuite_1554456729008/work/src/ffindexdatabase.cpp:11: FFindexDatabase:
> 
> - 14:56:31.348 ERROR: 	could not open file &apos;/databases/hhsuite/pfam_cs219.ffdata&apos;
> </pre>
> ```
> 
> Seams it are trying to open an inexistent file `/opt/conda/conda-bld/hhsuite_1554456729008/work/src/ffindexdatabase.cpp` at an inexistent directory `/opt/conda/conda-bld/hhsuite_1554456729008/work/src/` in a base directory completely different from those is was installed `/home/linuxbrew/anaconda3`.
> 
> How do you suggest I solve it??
> 
> Thanks in advance

@acpguedes how did you solve this?  am encountering the same problem

thanks

**Comment by acpguedes** [comment]
@bluestreek2507 check the permissions of the files you downloaded.
It must be readable for any user `chmod 751 {file name}` or `for i in $( ls /databases/hhsuite/pdb70* ); do echo chmod 754 $i ; done` .

**Comment by ahcm** [comment]
`chmod a+r /databases/hhsuite/pdb70* `
