### ISSUE TITLE
Exporting hhm files from hh-suite database

### ISSUE THREAD

**Issue by smsaladi** [soedinglab/hh-suite#138]
Is it possible to export selected or even all HMMs from an hh-suite database into hh-suite-compatible `.hhm` files?c

Sorry if this is obvious. I'm still new to the formats here. And, thanks in advance.

**Comment by smsaladi** [comment]
Turns out to be pretty easy using `hhsuite.db` as an example as well as the utilities in `ffindex.py`. 

In case others stumble upon this question, here is a snippet that reads the output of result2msa and writes each MSA entry to a file.

```python

import os
import os.path
import sys
from argparse import ArgumentParser

from tqdm import tqdm

import ffindex

def read_database(db_basename):
  entries = ffindex.read_index(db_basename + ".ffindex")
  data = ffindex.read_data(db_basename + ".ffdata")

  for entry in tqdm(entries):
    yield entry.name, ffindex.read_lines(entry, data)

def check_dir(outdir):
  if not os.path.exists(outdir):
    os.makedirs(outdir)
  return


def write_to_files(db_basename, outdir):
  for name, data in read_database(db_basename):
    name = "{:09d}".format(int(name))
    subdir = '{}/{:05d}'.format(outdir, int(name) // 1000)
    check_dir(subdir)
    out_name = "{}/{}.a3m".format(subdir, name)
    with open(out_name, 'w') as fh:
      print(*data, sep='\n', file=fh)

  return
```

**Comment by milot-mirdita** [comment]
`ffindex_unpack` does the same thing.

We are currently all traveling/on holidays/etc. so support is kinda difficult.
