### ISSUE TITLE
The output of the hhpred is without pdb codes

### ISSUE THREAD

**Issue by Meravbraitbard** [soedinglab/hh-suite#142]
the output I get is with weird code and no the pdb code

## Expected Behavior
good example from old run (good one): 
No Hit                             Prob E-value P-value  Score    SS Cols Query HMM  Template HMM
  1 2DCE_A KIAA1915 protein; SWIRM  99.8 7.1E-25 1.2E-29  195.9   0.0   98   78-176    11-110 (111)
  2 2FQ3_A Transcription regulator  99.8   1E-24 1.8E-29  192.7   0.0   90   83-172    14-103 (104)
## Current Behavior

this run look like this:
 No Hit                             Prob E-value P-value  Score    SS Cols Query HMM  Template HMM
  1 tr|A0A0G2ICY1|A0A0G2ICY1_9PEZI 100.0  1E-109  5E-115  902.2   0.0  436   55-492    66-612 (656)
  2 tr|A7TNN3|A7TNN3_VANPO Putativ 100.0  4E-108  2E-113  881.3   0.0  523    5-557    10-550 (550)

## Steps to Reproduce (for bugs)
I try to run it few times and I downloaded the pdb database twice
## HH-suite Output (for bugs)
Query         RSC8
Match_columns 557
No_of_seqs    2082 out of 3832
Neff          5.86959
Searched_HMMs 28650
Date          Sun May 12 11:27:05 2019
Command       /cs/usr/meravb/bio3d/Programs/hh-suite/bin/hhblits -d /mnt/local/meravb/hhpred_database/uniclust30_2017_10/uniclust30_2017_10 -i /cs/usr/meravb/new_dir/RSC/HHpred_search/search_apr_2019/fasta_files/RSC8.fasta -oa3m RSC8.oa3m -n 4 -Z 250 -z 1 -b 1 -B 250 ...

## Context
I want to compare this run to older ones and now it is not possible 

## Your Environment
Linux

**Comment by milot-mirdita** [comment]
You are missing the second search step against the PDB, you can do this either with `hhsearch` or with `hhblits -n 1` (this will be less sensitive but faster).

You can download the database here:
http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/

**Comment by Meravbraitbard** [comment]
I am not sure that I understand, this is the commands that I ran:
 ~/bio3d/Programs/hh-suite/bin/hhsearch  -d hhpredd_database  -i  fasta
~/bio3d/Programs/hh-suite/bin/hhblits  "-d  + uniclast_database   -i  fasta  -oa3m oa3m_file -e 1e-3 -n 1 -p 20 -Z 250 -z 1 -b 1 -B 250
~/bio3d/Programs/hh-suite/bin/hhblits  -d  uniclast_database  -i  fasta  -oa3m oa3m_file  -n 4  -Z 250 -z 1 -b 1 -B 250
~/bio3d/Programs/hh-suite/bin/hhsearch  -d hhpredd_database  -i " + oa3m_file -p 20 -Z 250 -loc -z 1 -b 1 -B 250 -ssm 2 -sc 1 -seq 1 -dbstrlen 10000 -norealign -maxres 32000 -contxt /cs/usr/meravb/bio3d/Programs/hh-suite/bin/../data/context_data.crf

What is missing here?
Thanks

**Comment by milot-mirdita** [comment]
The output you posted is what I expect to be produced by this call:
```
~/bio3d/Programs/hh-suite/bin/hhblits -d uniclast_database -i fasta -oa3m oa3m_file -n 4 -Z 250 -z 1 -b 1 -B 250
```

The output you expect is the output that should be produced by this call:
```
~/bio3d/Programs/hh-suite/bin/hhsearch -d hhpredd_database -i " + oa3m_file -p 20 -Z 250 -loc -z 1 -b 1 -B 250 -ssm 2 -sc 1 -seq 1 -dbstrlen 10000 -norealign -maxres 32000 -contxt /cs/usr/meravb/bio3d/Programs/hh-suite/bin/../data/context_data.crf
```

There are a few weird things in your calls that I assume are copy paste issues (`-i " +` and `"-d`).

**Comment by Meravbraitbard** [comment]
I looked again and I found the problem, this is the warning that I get:
ERROR: Could find neither hhm_db nor a3m_db!
In the db files I have a link do this DB's.
![image](https://user-images.githubusercontent.com/35961807/58100311-0d755a80-7be6-11e9-837a-8f412aeb8c05.png)
Do you know why I get this warning,
Thanks again

**Comment by milot-mirdita** [comment]
Can you post the exact call to hhsearch and the complete corresponding output?

**Comment by Meravbraitbard** [comment]
my call:
hhpred_script  -d /mnt/local/meravb/hhpred_database/pdb70  -i  oa3m_file -p 20 -Z 250 -loc -z 1 -b 1 -B 250 -ssm 2 -sc 1 -seq 1 -dbstrlen 10000 -norealign -maxres 32000 -contxt /cs/usr/meravb/bio3d/Programs/hh-suite/bin/../data/context_data.crf

the complete corresponding output:

- 16:19:12.135 INFO: Search results will be written to /cs/usr/meravb/new_dir/RSC/HHpred_search/search_apr_2019/fasta_files/RSC2.hhr!

- 16:19:12.135 ERROR: Could find neither hhm_db nor a3m_db!

**Comment by milot-mirdita** [comment]
Could you please execute:
```
ls -lah /mnt/local/meravb/hhpred_database/pdb70*
```

**Comment by Meravbraitbard** [comment]
-rw-r--r-- 1 meravb dina_lab  15G May  8 16:20 /mnt/local/meravb/hhpred_database/pdb70_from_mmcif_190501.tar.gz

/mnt/local/meravb/hhpred_database/pdb70_from_mmcif_190501:
total 41G
drwxr-Sr-- 2 meravb dina_lab 4.0K May 12 09:33 ./
drwxr-Sr-- 7 meravb dina_lab 4.0K May 12 09:22 ../
-rw------- 1 meravb dina_lab  614 May  1 20:51 md5sum
lrwxrwxrwx 1 meravb dina_lab   16 May  1 20:49 pdb70_a3m_db -> pdb70_a3m.ffdata
-rw------- 1 meravb dina_lab 1.8M May  1 20:49 pdb70_a3m_db.index
-rw------- 1 meravb dina_lab  39G May  1 20:49 pdb70_a3m.ffdata
-rw------- 1 meravb dina_lab 1.6M May  1 20:49 pdb70_a3m.ffindex
-rw------- 1 meravb dina_lab 6.9M May  1 03:35 pdb70_clu.tsv
-rw------- 1 meravb dina_lab  17M May  1 20:49 pdb70.cs219
-rw------- 1 meravb dina_lab  16M May  1 20:45 pdb70_cs219.ffdata
-rw------- 1 meravb dina_lab 1.2M May  1 20:45 pdb70_cs219.ffindex
-rw------- 1 meravb dina_lab   14 May  1 20:49 pdb70.cs219.sizes
lrwxrwxrwx 1 meravb dina_lab   16 May  1 20:49 pdb70_hhm_db -> pdb70_hhm.ffdata
-rw------- 1 meravb dina_lab 1.7M May  1 20:49 pdb70_hhm_db.index
-rw------- 1 meravb dina_lab 2.5G May  1 20:49 pdb70_hhm.ffdata
-rw------- 1 meravb dina_lab 1.4M May  1 20:49 pdb70_hhm.ffindex
-rw------- 1 meravb dina_lab  18M May  1 03:35 pdb_filter.dat

**Comment by milot-mirdita** [comment]
Please use `/mnt/local/meravb/hhpred_database/pdb70_from_mmcif_190501/pdb70` for the database name for HHsearch.

**Comment by Meravbraitbard** [comment]
It's working now,
Thanks a lot!
