### ISSUE TITLE
Probability calculation method is not aware of the secondary structure

### ISSUE THREAD

**Issue by dvs** [soedinglab/hh-suite#161]
Hit::CalcProbab calculates probability in two slightly different ways, depending on
the fact whether the SS was actually used. However, both ssm1 and ssm2 fields are not initialized and thus the probability is calculated always in one way.

HH-Suite v.2.0.x code has Hit::InitializeForAlignment method which does the job of setting ssm1 and ssm2 fields. HH-Suite v.3.x misses this function, i.e. this is a regression.

**Comment by dvs** [comment]
With this patch HH-Suite v.3.x produces (almost?) the same output as HH-Suite v.2.0.16 when MAC realignment is disabled, and the following options are used:

    -pc_hhm_contxt_a 1 -pc_hhm_contxt_b 1.5 -pc_hhm_contxt_c 1 -contxt $HHLIB/data/context_data.lib

In some use cases it is important to know how to reproduce with v.3.x versions old results generated by HH-Suite v.2.x. User Guide describes new features and new option defaults but it does not specify exactly the "compatibility" options' set that would mimic v.2.x behaviour.
Perhaps now when the probability is/would be fixed this knowledge could be added to the User Guide.

**Comment by martin-steinegger** [comment]
HH-suite should now use the SS information in the FW/BW algorithm again. Thank you! 👍
