### ISSUE TITLE
To all HHSUITE users - Which uniclust30 did you download / use?

### ISSUE THREAD

**Issue by gnmcsbnfrmtcsclb** [soedinglab/hh-suite#167]
What are the 2 links to uniclust30 databases? And how are they different?

One link is for uniclust30_2018_08_hhsuite.tar.gz = 25G at 
http://gwdu111.gwdg.de/~compbiol/uniclust/2018_08/uniclust30_2018_08_hhsuite.tar.gz

Another links is for uniclust30_2018_08.tar.gz = 6.6G at
http://gwdu111.gwdg.de/~compbiol/uniclust/2018_08/uniclust30_2018_08.tar.gz

I'm using the latter uniclust30_2018_08
But I wonder whether I should be using uniclust30_2018_08_hhsuite

Can anyone advice? Thanks!

**Comment by martin-steinegger** [comment]
uniclust30_2018_08_hhsuite.tar.gz is correct.

uniclust30_2018_08.tar.gz is not a HHsuite database, it is a fasta file containing only the representative sequences of the clusters.

**Comment by gnmcsbnfrmtcsclb** [comment]
Thanks for clarifying, Martin. Cheers!
