### ISSUE TITLE
conda installation error

### ISSUE THREAD

**Issue by sejmodha** [soedinglab/hh-suite#170]
Unable to install hhsuite using conda 4.7.12 
## Current Behavior
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package openmp conflicts for:
hhsuite -> openmp
Package libstdcxx-ng conflicts for:
hhsuite -> libstdcxx-ng[version='>=7.3.0']
Package libgcc-ng conflicts for:
hhsuite -> libgcc-ng[version='>=7.3.0']
Package python conflicts for:
hhsuite -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
Package perl conflicts for:
hhsuite -> perl[version='>=5.26.2,<5.26.3.0a0']
```

## Your Environment

```
     active environment : myenv
    active env location : /home/../anaconda3/envs/myenv
            shell level : 2
       user config file : /home/../.condarc
 populated config files : /home/../.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages :
       base environment : /home/../anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/../anaconda3/pkgs
                          /home/../pkgs
       envs directories : /home/../anaconda3/envs
                          /home/../envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/4.15.0-55-generic ubuntu/18.04.3 glibc/2.27
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False

```

**Comment by milot-mirdita** [comment]
Does this also happen when you create a new environment?

Please try executing:
``
conda create -n hhsuite hhsuite
conda activate hhsuite
hhblits
```

It seems like some existing package in your `myenv` environment is conflicting with the hh-suite.

**Comment by jameswagstaff** [comment]
Hi I am also having this problem. I tried creating a new env as follows:

```
(base) Jamess-MacBook-Pro:~ jameswagstaff$ conda create -n hhsuite -c bioconda hhsuite
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                               

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package openmp conflicts for:
hhsuite -> openmp
Package libcxx conflicts for:
hhsuite -> libcxx[version='>=4.0.1']
Package llvm-openmp conflicts for:
hhsuite -> llvm-openmp
Package python conflicts for:
hhsuite -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
Package perl conflicts for:
hhsuite -> perl[version='>=5.26.2,<5.26.3.0a0']
```

**Comment by milot-mirdita** [comment]
I can't reproduce the issue on a fresh conda installation on macOS 10.14. It seems like there is something wrong with your conda.

```
$ conda --version
conda 4.7.12
```

**Comment by lpravda** [comment]
I can confirm the same error. I tried conda on two different environments. First was our linux cluster with Red Hat 7.4. The other one was on my mac running macOS 10.15.3. Both of the installations have the latest conda 4.8.2. I tried creating a fresh environment using:

`conda create -n cov-env -c bioconda hhsuite`

but failing with the following error message in both of the cases.

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError:
```

When I try to install the package into an existing conda environment (running python 3.7.6) I get the following error:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

I am no expert in conda, but brief check of hhsuite dependecies reveals the following:
hhsuite asks, among others, for `libcxx >=4.0.1` and `llvm-openmp >=8.0.1`. **This to my understanding can never be satisfied**. The last available versions for both of the packages are `9.0.1` and `4.0.1` (check it here: https://anaconda.org/anaconda/llvm-openmp/files and here: https://anaconda.org/conda-forge/libcxx/files ). Is it somehow possible that there is a typo in the hhsuite dependencies definitions and the correct requirements should be: `libcxx >=8.0.1` and `llvm-openmp >=4.0.1`

**Comment by milot-mirdita** [comment]
Okay i think I know whats wrong. You are missing the `conda-forge` channel. Installing hh-suite with only `defaults` and `bioconda` results in the error above.

This should work:
```
conda create -n cov-env -c conda-forge -c bioconda hhsuite
```

**Comment by milot-mirdita** [comment]
@lpravda Thanks a lot. Because of your hint I was also able to fix the same problem in the installation instructions in MMseqs2 and Plass. If you want a set of stickers (see https://twitter.com/thesteinegger/status/1201076220957315074), send me your address to milot at mirdita de.

**Comment by lpravda** [comment]
Nice find! I didn't not actually notice that google pointed me to two different channels in the links I provided, but I'm glad you figured out what is happening. +1 for the stickers, it looks amazing!

**Comment by SLS79** [comment]
Hi, 

I'm sorry if this is a stupid question. But i just downloaded Conda, and I am trying to install HH suite but i cannot find it using Anaconda navigator (i have conda-forge to my channels). 

I tried typing the following code into Anaconda Prompt: conda install -c conda-forge -c bioconda hhsuite   
But is says "PackagesNotFoundError".  Specifically, this error message. 

- hhsuite

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/win-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org


Sorry to bother you
