### ISSUE TITLE
no local alignment by hhalign

### ISSUE THREAD

**Issue by rattei** [soedinglab/hh-suite#174]
Dear developers,

in many hhm/hhm comparisons, the current 3.2.0 version of hhalign gives a result header but no alignment. Both sse and aux versions of hhalign are affected.

Steps to reproduce:
``[rattei@cubea01 vog]$ module unload hhsuite; module load hhsuite/3.2.0-sse2 
[rattei@cubea01 vog]$ hhalign -i 559719477.hhm -t 1000005916.hhm -v 0 -o stdout
Query         nCLS00604
Match_columns 303
No_of_seqs    10 out of 10
Neff          2.3
Searched_HMMs 1
Date          Sat Oct 19 13:57:43 2019
Command       hhalign -i 559719477.hhm -t 1000005916.hhm -v 0 -o stdout 

 No Hit                             Prob E-value P-value  Score    SS Cols Query HMM  Template HMM

[rattei@cubea01 vog]$
``

``[rattei@cubea01 vog]$ module load hhsuite/3.0-beta.3 
[rattei@cubea01 vog]$ rm 559719477.hhr
[rattei@cubea01 vog]$ hhalign -i 559719477.hhm -t 1000005916.hhm -v 0
[rattei@cubea01 vog]$ cat 559719477.hhr
Query         nCLS00604
Match_columns 303
No_of_seqs    10 out of 10
Neff          2.3
Searched_HMMs 1
Date          Sat Oct 19 13:55:10 2019
Command       hhalign -i 559719477.hhm -t 1000005916.hhm -v 0 

 No Hit                             Prob E-value P-value  Score    SS Cols Query HMM  Template HMM
  1 pCLS10324                        0.2    0.32    0.32   11.4   0.0    4  135-138    27-30  (44)

No 1
>pCLS10324
Probab=0.19  E-value=0.32  Score=11.37  Aligned_cols=4  Identities=50%  Similarity=1.522  Sum_probs=1.7  Template_Neff=1.400

Q t1027232p2_1_3  135 IWIC  138 (303)
Q Consensus       135 VWi~  138 (303)
                      .|||
T Consensus        27 gfiC   30 (44)
T t1327952p50_1_   27 AFIC   30 (44)
Confidence            3444

[rattei@cubea01 vog]$
``

Both hhm files are attached.

Environment:
Centos 7.3, hhsuite binary files 3.2.0 from GitHub

Best,
Thomas

[hhm.zip](https://github.com/soedinglab/hh-suite/files/3746663/hhm.zip)

**Comment by martin-steinegger** [comment]
This issues should be fixed now. 

The issues occurred because we remove alignments that are too short. I have set the min. length for alignments to 1 for hhalign.

**Comment by rattei** [comment]
Thanks so much, Martin!!

best regards,
Thomas
