### ISSUE TITLE
Hh-search does not work on *.pal files

### ISSUE THREAD

**Issue by goaaron** [soedinglab/hh-suite#176]
## Expected Behavior
hhsearch -i  input.hmm -d hmms.pal should work
## Current Behavior
 ERROR: Could find neither hhm_db nor a3m_db!
## Context
I am doing hhsearch on hmms i build on the fly during clustering

## Your Environment
hhsuite 2.0.16. mac osx

**Comment by martin-steinegger** [comment]
@goaaron how does your database files look like? Your need a hmms.pal_hhm_db.ffdata and  hmms.pal_hhm_db.ffindex.

**Comment by goaaron** [comment]
@martin-steinegger  
The .pal file contains new-line separated list of paths to individual hhms. 
Referencing: http://sysbio.rnet.missouri.edu/bdm_download/DeepRank_db_tools/tools/DNCON2/hhsuite-2.0.16-linux-x86_64/hhsuite-userguide.pdf

So, I need to concatenate them and build the db with ffindex_build?
