### ISSUE TITLE
hhpred fails to create directory in /tmp

### ISSUE THREAD

**Issue by steveped** [soedinglab/hh-suite#177]
We have managed to get a local install (nearly) working on Ubuntu 18.04. The install is in `/opt/hh-suite/`. We've edited both copies of HHpaths.pm and the process runs successfully for much of it's course. However, it appears an important directory in `/tmp` is not being created before running `hhfilter`. The relevant section from capturing stderr to a log file seems to be:

```
[omitted text showing success]

- 17:32:35.327 INFO: Realigning 500 HMM-HMM alignments using Maximum Accuracy algorithm

- 17:32:48.149 INFO: 14551 sequences belonging to 14551 database HMMs found with an E-value < 0.001

- 17:32:48.152 INFO: Number of effective sequences of resulting query HMM: Neff = 10.6823

$ cp /tmp/14611/Q18C34/Q18C34NrfcHVD.a3m /tmp/51IzPV5bWi/jkJ4vMX9to.1.in.a3m
Filtering alignment to diversity 7 ...
$ hhfilter -v 1 -neff 7 -i /tmp/51IzPV5bWi/jkJ4vMX9to.in.a3m -o /tmp/51IzPV5bWi/jkJ4vMX9to.in.a3m
$ /opt/hh-suite/scripts/reformat.pl -v 1 -r -noss a3m psi /tmp/51IzPV5bWi/jkJ4vMX9to.in.a3m /tmp/51IzPV5bWi/jkJ4vMX9to.in.psi
Predicting secondary structure with PSIPRED ... $ /opt/toolkit/ncbi/bin/blastpgp -b 1 -j 1 -h 0.001 -d /opt/hh-suite/data/do_not_delete -i /tmp/51IzPV5bWi/jkJ4vMX9to.sq -B /tmp/51IzPV5bWi/jkJ4vMX9to.in.psi -C /tmp/51IzPV5bWi/jkJ4vMX9to.chk 1> /tmp/51IzPV5bWi/jkJ4vMX9to.blalog 2> /tmp/51IzPV5bWi/jkJ4vMX9to.blalog

Error: command '/opt/toolkit/ncbi/bin/blastpgp -b 1 -j 1 -h 0.001 -d /opt/hh-suite/data/do_not_delete -i /tmp/51IzPV5bWi/jkJ4vMX9to.sq -B /tmp/51IzPV5bWi/jkJ4vMX9to.in.psi -C /tmp/51IzPV5bWi/jkJ4vMX9to.chk 1> /tmp/51IzPV5bWi/jkJ4vMX9to.blalog 2> /tmp/51IzPV5bWi/jkJ4vMX9to.blalog' returned error code 127
```

The key error seems to be occurring before the following line, where the source file exists & has been created (`/tmp/14611/Q18C34/Q18C34NrfcHVD.a3m`), but the target directory (` /tmp/51IzPV5bWi/`) is not being created.

```
cp /tmp/14611/Q18C34/Q18C34NrfcHVD.a3m /tmp/51IzPV5bWi/jkJ4vMX9to.1.in.a3m
```

These file paths clearly change every time the process is run, but we see the same behaviour every time in that the target directory is never created. I'm assuming all downstream errors are generated by this file not being where it's expected to be (i.e. `/tmp/51IzPV5bWi/jkJ4vMX9to.1.in.a3m` in this instance). Considering the `cp` will have failed, it's pretty clear that the call to `hhfilter` will fail, as will everything else subsequent

If it's helpful, the command we have run is:

```
./hhpred.pl -i /opt/protein_db/Q18C34.seq -o ~/hhtest/testresult.pdb 2> ~/hhtest/hhpred.test.log
```

The git commit we've used is `ce0a82faa3` on Ubuntu 18.04

Thanks in advance for you help.

**Comment by steveped** [comment]
Resolved

**Comment by pavlohrab** [comment]
Greetings, how you resolved this issue?

> Resolved

**Comment by steveped** [comment]
This was several months ago so I can't quite remember. We ended using a docker image instead for the final analysis which had other tools incorporated. `bordin89/icb` was the image
