### ISSUE TITLE
-- Performing Test HAVE_AVX2_EXTENSIONS - Failed -- Performing Test HAVE_AVX_EXTENSIONS -- Performing Test HAVE_AVX_EXTENSIONS - Failed

### ISSUE THREAD

**Issue by YanpingHu** [soedinglab/hh-suite#179]
when I run "cmake -DCMAKE_INSTALL_PREFIX=. .."
I find a failed information：
**-- Performing Test HAVE_AVX2_EXTENSIONS
-- Performing Test HAVE_AVX2_EXTENSIONS - Failed
-- Performing Test HAVE_AVX_EXTENSIONS
-- Performing Test HAVE_AVX_EXTENSIONS - Failed_**

Then I run "make -j 4 && make install",I find there is no failed information.
I want to ask if the failed information will influence the future analysis  reslut?
Thank you very much for solving my problem!

**Comment by milot-mirdita** [comment]
If your CPU does not support the AVX2 instruction set it will fall back to the slower SSE2 based code. This will not have any influence on correctness, only on speed. See the recent publication in BMC Bioinformatics for details on the vectorized algorithms.
