### ISSUE TITLE
Where to find source code for older versions of hh-suite?

### ISSUE THREAD

**Issue by asowani** [soedinglab/hh-suite#18]
Hi! I tried to build hh-suite on Power8/LE but was getting a lot of SSE related issues. I wanted to have a look at older code to see what was there before implementing SSE related optimizations, however on GitHub only 3.0-beta code is available. I could not find any trace of older code in the existing code base as well. So where can I get older code of hh-suite? I did obtain version 2.0.16 code from one of Ubuntu source repositories but anything older than that is also desirable.

Thanks!
Atul.

**Comment by meiermark** [comment]
You can find older releases here: http://wwwuser.gwdg.de/~compbiol/data/hhsuite/releases/all/

However, they might contain bugs already fixed in the newest commit on github.

**Comment by asowani** [comment]
Thanks @meiermark! I just want to have a look at older code to get some idea about SSE changes.
