### ISSUE TITLE
prefilter in hhblits takes hours

### ISSUE THREAD

**Issue by patrickbryant1** [soedinglab/hh-suite#185]
:exclamation: Make to check out our [User Guide](https://github.com/soedinglab/hh-suite/wiki).

## Expected Behavior
I downloaded and installed:  hhsuite version 3.1.0 (20190520)
This has worked fine for me, searching uniprot20_2016_02.
## Current Behavior
When I run hhblits against uniclust 30 downloaded from:
wget http://wwwuser.gwdg.de/~compbiol/uniclust/2018_08/uniclust30_2018_08_hhsuite.tar.gz
tar -xvzf /home/p/pbryant/pfs/data/uniclust30/uniclust30_2018_08_hhsuite.tar.gz
the prefiltering step takes hours. I am using the following options:
$HHBLITS -i $CHAIN -d $HHBLITSDB -e 0.001 -cpu 4 -all -oa3m $CHAIN.a3m
and running on:
Intel Xeon E5-2690v4 | 2x14 cores

## Steps to Reproduce (for bugs)
See above.
I ran e.g. this sequence:
>11as_A
MKTAYIAKQRQISFVKSHFSRQLEERLGLIEVQAPILSRVGDGTQDNLSGAEKAVQVKVKALPDAQFEVVHSLAKWKRQT
LGQHDFSAGEGLYTHMKALRPDEDRLSPLHSVYVDQWDWERVMGDGERQFSTLKSTVEAIWAGIKATEAAVSEEFGLAPF
LPDQIHFVHSQELLSRYPDLDAKGRERAIAKDLGAVFLVGIGGKLSDGHRHDVRAPDYDDWSTPSELGHAGLNGDILVWN
PVLEDAFELSSMGIRVDADTLKHQLALTGDEDRLELEWHQALLRGEMPQTIGGGIGQSRLTMLLLQLPHIGQVQAGVWPA
AVRESVPSLL

## HH-suite Output (for bugs)
Normal output, time is the problem.

## Your Environment
Include as many relevant details about the environment you experienced the issue in.
* Version/Git commit used:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
Intel Xeon E5-2690v4 | 2x14 cores
Kebnekaise cluster: https://www.hpc2n.umu.se/resources/hardware/kebnekaise
* Operating system and version:
All nodes are running Ubuntu Xenial (16.04 LTS).

**Comment by martin-steinegger** [comment]
Could you please provide a log? How did you install hhsuite?

**Comment by patrickbryant1** [comment]
- 13:14:57.091 INFO: Search results will be written to 11as_A.hhr

- 13:15:10.490 INFO: Searching 15161831 column state sequences.

- 13:15:10.572 INFO: 11as_A.fa is in A2M, A3M or FASTA format

- 13:15:10.572 INFO: Iteration 1

**- 13:15:10.868 INFO: Prefiltering database**

**- 17:46:34.007 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 240449**

- 17:46:36.539 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 239

- 17:46:36.539 INFO: HMMs passed 2nd prefilter and not found in previous iterations : 239

- 17:46:36.539 INFO: Scoring 239 HMMs using HMM-HMM Viterbi alignment

I cloned the git and followed the instructions: https://github.com/soedinglab/hh-suite

**Comment by patrickbryant1** [comment]
I think there is a file access problem at the cluster I am using that seems to halt the process (which I did not get any error about). I apologize for any inconvenience and thank you for your time.
