### ISSUE TITLE
coverting cs219 file in uniclust

### ISSUE THREAD

**Issue by kad-ecoli** [soedinglab/hh-suite#188]
In http://gwdu111.gwdg.de/~compbiol/uniclust/2020_01/UniRef30_2020_01_hhsuite.tar.gz
there is no
UniRef30_2020_01.cs219.sizes or UniRef30_2020_01.cs219
Is it possible to covert UniRef30_2020_01_cs219.ffdata and UniRef30_2020_01_cs219.ffindex
into UniRef30_2020_01.cs219.sizes or UniRef30_2020_01.cs219? I understand that hhsuite2 is deprecated. However, our pipeline still depends heavily on hhsuite2, which in our case gives better result than hhsuite3.

This issue is related to https://github.com/soedinglab/hh-suite/issues/13
but I cannot find the script uploaded by milot-mirdita

**Comment by milot-mirdita** [comment]
We don't support HHsuite 2.x anymore, sorry! If you can point to specific examples where HHsuite 2.x performs better than the new versions we'd be happy to investigate them.

**Comment by kad-ecoli** [comment]
I am not entirely sure whether we have the same definition of "better". For the purpose for contact prediction (both by ccmpred and by third party program), MSA generated by hhbilts2 search on uniclust30 consistently results in better top L contact prediction accuracy than hhblits3 on the same database. I can prepare a dataset to demonstrate this, but it will take some time.

Since the goal of our project is to use hhblits generated MSA for contact prediction, secondary structure, and for generation of sequence profile for threading, rather than directly use hhblits2 for threading, all our tasks benefit from the usage of hhblits2 rather than hhblits3. Therefore, it is quite inconvenient that uniclust30 decides to drop support for hhblits2.

**Comment by kad-ecoli** [comment]
By the way, we do have an extreme example of poor performance of hhblits3 compared to hhblits2 for PDB target 3e7u
reported at https://github.com/soedinglab/uniclust-pipeline/issues/3
but it was never followed up.

Do you mind keeping this issue open until we have figured out the hhblits3 vs hhblits2 performance discrepancy?

**Comment by milot-mirdita** [comment]
Could you make a new issue please? Also I'd appreciate if you could try the current git version, as there were some important fixes contributed from users in the recent months. We are going to pack up everything into a new release soonish.

**Comment by kad-ecoli** [comment]
OK, I have opened another issue at
https://github.com/soedinglab/hh-suite/issues/205
