### ISSUE TITLE
Most recent (2020) Uniclust30 db potential formatting error. 

### ISSUE THREAD

**Issue by Groovy-Dragon** [soedinglab/hh-suite#192]
Hi there!

I've been manually going through the most recent Uniclust30 set (UniRef30_2020_01_hhsuite.tar.gz) and working with the _a3m.ffdata file and I noticed something that might be an issue. 

The target sequence for each cluster, being the sequence after the consensus sequence, seems to look like its a separate part of the alignment. For example a good number of these target sequences have gaps and inserts. The sequences seem to share the same Uni ID and description as the cluster as well. 

An example (double spaced for readability): 
`#UniRef100_A0A1L3ZU66 Uncharacterized protein n=1 Tax=Sphingomonas sp. JJ-A5 TaxID=1921510 RepID=A0A1L3ZU66_9SPHN`

`>UniRef100_A0A1L3ZU66_consensus`

`MMMRTRLLPLALALALALAACDRAAPPPAAVPDAASPPASADAPAPAAERTSSLPADFIVSTNEPFWQARVEGGTVVLSGPDGERRLAVASSQATGGGRRVVASDAAGSVELRVTPEPCQDSMSGAAFPFTGRLSIDGGEPIRGCARPASMPPPGEPGVPEPAPGADGASVPEGGEPGNVEGASPPPAA`

`>UniRef100_A0A1L3ZU66 Uncharacterized protein n=1 Tax=Sphingomonas sp. JJ-A5 TaxID=1921510 RepID=A0A1L3ZU66_9SPHN`

`--MRALTaGPTLIMLAMALAGCaSREAEPPAAAADEAVQPPKEEAPPMVRP--SSADVDWLAAGNEPGWRVEIDEGTLLDYTGDyGALRImtpAPATELLPGGARRWSVATEGHRLTLELSPVACTDDMSGAAYPMTARLTVDGKE-LRGCGRPG----------------------------------------`

As far as I can tell the sequence in uniprot with the corresponding ID has the same sequence as the gapped and inserted target sequence so I'm a bit confused as to why this is. 

Is this intended, and the consensus sequence is actually the target sequence? There's also a good chance I've missed something and not understanding so apologies if I've misunderstood something. 

Thanks for any help

**Comment by Groovy-Dragon** [comment]
Thinking on it, I now realize that the current uniclust ffdata is an actual set of alignments where as previously how it was stored was not as an alignment.

**Comment by milot-mirdita** [comment]
Previously it was also an alignment, just in our A3M format, which handles gappy columns more space-efficiently. Nothing should have really changed in the format. 

The consensus sequence is used in very few places, any scoring happens with hidden-markov-model(HMM) vs HMM scoring or sequence vs HMM scoring. I guess we only use the consensus to present pairwise alignments (didn't double-check this).
