### ISSUE TITLE
AA scoring matrix indexing error in FullAlignment::Build detected by Clang sanitizer

### ISSUE THREAD

**Issue by dvs** [soedinglab/hh-suite#196]
Clang undefined behavior sanitizer (UBSAN) reports that there might be wrong score indexing in FullAlignment::Build when aa2i() detects unknown AA letter (X,J,O = ANY):

    hh-suite/src/hhfullalignment.cpp:159:20: runtime error: index 20 out of bounds for type 'const float [20]'

See line 159:

    score_sim += S[(int) aa2i(qc)][(int) aa2i(tc)];

**Comment by milot-mirdita** [comment]
Could you check if  92c5adc fixes the ubsan error? I am not sure what sequences to use to reproduce the issue. Using a sequence with only X does not trigger the warning.

**Comment by dvs** [comment]
> Could you check if [92c5adc](https://github.com/soedinglab/hh-suite/commit/92c5adcf9313ec6fd8e7ea0c67340beb56473b0c) fixes the ubsan error? I am not sure what sequences to use to reproduce the issue. Using a sequence with only X does not trigger the warning.

Yes, I've checked this and it does fix the UBSAN error.
Thank you!
