### ISSUE TITLE
Problem HHSuite - Segmentation fault

### ISSUE THREAD

**Issue by dcerdanv** [soedinglab/hh-suite#199]
:exclamation: Make to check out our [User Guide](https://github.com/soedinglab/hh-suite/wiki).

## Expected Behavior
Run hhblits and then addss to optain a .a3m file.

## Current Behavior
When it is running hhblits it works properly until it is stopped due to a "Segmentation fault (core dumped)" always in the same point for every file. After that addss can be executed with no problem.

## Steps to Reproduce (for bugs)
It is hard to reproduce the full context of the program, but the call to hhblits (and then addss.pl to add the secondary structure) is just:
hhblits -i $dir/$chad.chd -d $DB_dir/$seq_DB/$seq_DB -oa3m $dir_output/$chad.a3m
perl $directo/scripts/addss.pl $dir_output/$chad.a3m

I tried to change the -maxres, -maxmen and -cpu parameters as it is said in the wiki; and also I let to overcomit the memory (vm.overcommit_memory=1) but the problem persists.

## HH-suite Output (for bugs)
The output of one call is:

Call to hhblits!!!
- 17:11:41.301 INFO: Searching 80534 column state sequences.

- 17:11:41.406 INFO: /localHDD/nuevo_fireDB/firedb_actualizacion/firestar/fdbrun/HH_DB_update/chads_28Jan2020/5xg2A.chd is in A2M, A3M or FASTA format

- 17:11:41.406 INFO: Iteration 1

- 17:11:41.787 INFO: Prefiltering database

- 17:11:42.698 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 1728

- 17:11:42.727 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 684

- 17:11:42.727 INFO: HMMs passed 2nd prefilter and not found in previous iterations : 684

- 17:11:42.727 INFO: Scoring 684 HMMs using HMM-HMM Viterbi alignment

- 17:11:42.785 INFO: Alternative alignment: 0

- 17:11:43.549 INFO: 684 alignments done

- 17:11:43.551 INFO: Alternative alignment: 1

- 17:11:44.086 INFO: 407 alignments done

- 17:11:44.087 INFO: Alternative alignment: 2

- 17:11:44.407 INFO: 204 alignments done

- 17:11:44.407 INFO: Alternative alignment: 3

- 17:11:44.601 INFO: 91 alignments done

- 17:11:44.641 INFO: Realigning 311 HMM-HMM alignments using Maximum Accuracy algorithm

- 17:11:47.016 INFO: 13 sequences belonging to 13 database HMMs found with an E-value < 0.001

- 17:11:47.016 INFO: Number of effective sequences of resulting query HMM: Neff = 4.5973

- 17:11:47.110 INFO: Iteration 2

- 17:11:47.594 INFO: Prefiltering database

- 17:11:48.430 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 1840

- 17:11:48.465 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 755

- 17:11:48.487 INFO: HMMs passed 2nd prefilter and not found in previous iterations : 742

- 17:11:48.487 INFO: Scoring 742 HMMs using HMM-HMM Viterbi alignment

- 17:11:48.573 INFO: Alternative alignment: 0

- 17:11:49.214 INFO: 742 alignments done

- 17:11:49.216 INFO: Alternative alignment: 1

- 17:11:49.712 INFO: 500 alignments done

- 17:11:49.713 INFO: Alternative alignment: 2

- 17:11:50.075 INFO: 339 alignments done

- 17:11:50.075 INFO: Alternative alignment: 3

- 17:11:50.396 INFO: 175 alignments done

- 17:11:50.445 INFO: Realigning 333 HMM-HMM alignments using Maximum Accuracy algorithm

- 17:11:52.223 INFO: 16 sequences belonging to 16 database HMMs found with an E-value < 0.001

- 17:11:52.223 INFO: Number of effective sequences of resulting query HMM: Neff = 7.28706

- 17:11:52.223 INFO: Rescoring previously found HMMs with Viterbi algorithm

- 17:11:52.256 INFO: Alternative alignment: 0

- 17:11:52.271 INFO: 13 alignments done

- 17:11:52.271 INFO: Alternative alignment: 1

- 17:11:52.278 INFO: 12 alignments done

- 17:11:52.278 INFO: Alternative alignment: 2

- 17:11:52.290 INFO: 12 alignments done

- 17:11:52.290 INFO: Alternative alignment: 3

- 17:11:52.313 INFO: 11 alignments done

Segmentation fault (core dumped)

Call to addss!!!
$ cp /localHDD/nuevo_fireDB/firedb_actualizacion/firestar/fdbrun/HH_DB_update/a3m_28Jan2020/5xg2A.a3m /tmp/qtl6K_lQfo/IqRjIRQrGM.in.a3m
Filtering alignment to diversity 7 ...
$ hhfilter -v 1 -neff 7 -i /tmp/qtl6K_lQfo/IqRjIRQrGM.in.a3m -o /tmp/qtl6K_lQfo/IqRjIRQrGM.in.a3m
$ /usr/share/hhsuite/scripts/reformat.pl -v 1 -r -noss a3m psi /tmp/qtl6K_lQfo/IqRjIRQrGM.in.a3m /tmp/qtl6K_lQfo/IqRjIRQrGM.in.psi
$ gunzip -c /localHDD/nuevo_fireDB/firedb_actualizacion/firestar/DB/GOLDEN_PDB/divided/xg/pdb5xg2.ent.gz > /tmp/1Niv5ezpx6
$ /usr/share/hhsuite/scripts/../../dssp-2.0.4/bin/dssp -i /tmp/1Niv5ezpx6 -o /tmp/qtl6K_lQfo/IqRjIRQrGM.dssp 2> /dev/null

Adding DSSP state sequence ...
Predicting secondary structure with PSIPRED ... $ /usr/share/hhsuite/scripts/../../blast-2.2.26/bin/blastpgp -b 1 -j 1 -h 0.001 -d /usr/share/hhsuite/data/do_not_delete -i /tmp/qtl6K_lQfo/IqRjIRQrGM.sq -B /tmp/qtl6K_lQfo/IqRjIRQrGM.in.psi -C /tmp/qtl6K_lQfo/IqRjIRQrGM.chk 1> /tmp/qtl6K_lQfo/IqRjIRQrGM.blalog 2> /tmp/qtl6K_lQfo/IqRjIRQrGM.blalog
$ echo IqRjIRQrGM.chk > /tmp/qtl6K_lQfo/IqRjIRQrGM.pn

$ echo IqRjIRQrGM.sq  > /tmp/qtl6K_lQfo/IqRjIRQrGM.sn

$ /usr/share/hhsuite/scripts/../../blast-2.2.26/bin/makemat -P /tmp/qtl6K_lQfo/IqRjIRQrGM
$ /usr/share/hhsuite/scripts/../../psipred-4.01/bin/psipred /tmp/qtl6K_lQfo/IqRjIRQrGM.mtx /usr/share/hhsuite/scripts/../../psipred-4.01/data/weights.dat /usr/share/hhsuite/scripts/../../psipred-4.01/data/weights.dat2 /usr/share/hhsuite/scripts/../../psipred-4.01/data/weights.dat3 > /tmp/qtl6K_lQfo/IqRjIRQrGM.ss
$ /usr/share/hhsuite/scripts/../../psipred-4.01/bin/psipass2 /usr/share/hhsuite/scripts/../../psipred-4.01/data/weights_p2.dat 1 0.98 1.09 /tmp/qtl6K_lQfo/IqRjIRQrGM.ss2 /tmp/qtl6K_lQfo/IqRjIRQrGM.ss > /tmp/qtl6K_lQfo/IqRjIRQrGM.horiz
done 

Notice than "Call to hhblits" or "Call to addss" are just two sentences that I printed to know what was failing. At the end I get the .a3m file, but probably incomplete because of the fault.

## Your Environment

I'm runing this in Ubuntu 18.04. In a 16 cores machine, each of them is a Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, and a RAM of 94GB.
I don't use any special enviroment, I tried with conda but I get more issues so I install everything directly in my machine.
I'm using:
- HHsuite 3.0.0 (i tried with 3.2.0 but it does not work neither.
- Blast 2.2.26
- Psired 4.01
- Dssp 2.0.4
- As DB i tried Uniprot20_2016_02, pdb70 and Uniref30_2020_02, always with the same result.

Thank you very much in advance.

**Comment by milot-mirdita** [comment]
Could you upload this `5xg2A.chd ` file? I can try to reproduce the issue with it.

**Comment by dcerdanv** [comment]
Do not worry milot-mirdita, it seens to be a problem of permissions.
When I runned it as sudo it gave memory problems, and when not it gave other differents.
Finally I could install it in conda and run it from there, without "sudo", and it is working now.

Thank you very much.
