### ISSUE TITLE
Wrong interpretation of  '-ssm' option

### ISSUE THREAD

**Issue by dvs** [soedinglab/hh-suite#2]
Dear HH-Suite developers,

It seems that '-ssm' option is not processed correctly by the HH-Suite tools.

When we compared HHalign v.2.0.16 vs. v.3.0.0 we observed that in spite of explicit identical settings
(-local -alt 10 -p 0 -norealign -pc_hhm_contxt_mode 2 -pc_hhm_contxt_a 1.0 -pc_hhm_contxt_b 1.5 -pc_hhm_contxt_c 1.0 -contxt /usr/.../data/context_data.lib) the new version does not take into account SS score when the alignment is constructed.

It turned out that due to a bug '-ssm 1' should be used instead '-ssm 2' option for setting the mode when SS score is used during the Viterbi algorithm.

Indeed, Hit::SCORE_ALIGNMENT constant is defined as 1 in hhhit.h: as a result when '-ssm 2' option is used (which is the default value) the comparison 'ss_mode == Hit::SCORE_ALIGNMENT' in Viterbi::Align() fails and SS score is not used during the Viterbi algorithm.

**Comment by meiermark** [comment]
Hello,

thank you very much for this bug report.
The secondary structure scoring is still under development.
However, I pushed a bugfix for this issue today.
