### ISSUE TITLE
hh-suite porting to Power8/LE.

### ISSUE THREAD

**Issue by asowani** [soedinglab/hh-suite#21]
Hi,

I am working on porting hh-suite to ppc64le. I would like to know if there is any CLA that needs to be signed to port hh-suite to ppc64le. This is because I need to change SSE specific code to AltiVec. To achieve this, I will need to comment out/write new code in simd.h file.

Also, I was checking the user guide which mentions that certain databases (uniprot20, nr20 etc.) are required for hh-suite. However I could not find those databases at wwwuser.gwdg.de/~compbiol/data/databases/hhsuite_dbs/ This link redirects to https://www.gwdg.de/ where I could not find any databases. So where do I find them?

Thanks,
Atul.

**Comment by martin-steinegger** [comment]
Hi Atul,

There is already an open issues for Power8/LE here https://github.com/soedinglab/hh-suite/issues/9? 
You can find the database here http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/

Best regards,
Martin

**Comment by milot-mirdita** [comment]
Where did you find the broken link to the HHsuite databases? I just checked the links in the user guide (on github).

**Comment by asowani** [comment]
This is strange - the PDF manual I have clearly has following link on page 8, section 2.4:
http://wwwuser.gwdg.de/~compbiol/data/databases/hhsuite_dbs/

However the link you've given works. Many thanks for the link!

Yes, this is similar to #9 but I could get past that issue and have actually built hh-suite on ppc64le. However, I would like to know if I need to sign any CLA for that.

Thanks,
Atul.

**Comment by milot-mirdita** [comment]
Wow, thanks a lot for your work! 

You should sign your git commits and send a pull request in which you state that you are submitting your contribution under GPLv3.

Which PDF manual is that? Do you remember where you downloaded it? We should fix that.

**Comment by asowani** [comment]
I think I was having an older copy of the manual. I cloned the source about 4-5 weeks ago and the PDF came along with that. The latest PDF in the source has correct link to databases. Thanks!
