### ISSUE TITLE
Fastest way to run HHblits on many different sequences?

### ISSUE THREAD

**Issue by tueboesen** [soedinglab/hh-suite#212]
I'm running HHblits in docker and I wish to run it on a whole dataset of sequences to find an MSA for each sequence.
However the only way I have found to do this yet, is to put each sequence in a different fasta file and then make a bash script (or in my case windows terminal script) that loops over all fasta files in a folder and runs HHblits on each one. 

However this seems to take about 10 minutes for each fasta file, and since I have about 25000 sequences I want to find a match for this will take a while. 

Here is a logfile from a run, especially the Prefiltering database seems to take a while.
```
docker : - 17:01:49.930 INFO: Search results will be written to /data/input/1.hhr
At E:\data\docker_images.ps1:10 char:5
+     docker run -v E:/data:/data soedinglab/hh-suite hhblits -i /data/ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (- 17:01:49.930 ...ata/input/1.hhr:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
- 17:02:00.988 INFO: Searching 24948541 column state sequences.
- 17:02:01.038 INFO: /data/input/1.fasta is in A2M, A3M or FASTA format
- 17:02:01.038 INFO: Iteration 1
- 17:02:01.286 INFO: Prefiltering database
- 17:09:43.438 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 592311
- 17:09:56.000 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 435
- 17:09:56.000 INFO: HMMs passed 2nd prefilter and not found in previous iterations : 435
- 17:09:56.000 INFO: Scoring 435 HMMs using HMM-HMM Viterbi alignment
- 17:09:57.029 INFO: Alternative alignment: 0
- 17:10:00.264 INFO: 435 alignments done
- 17:10:00.267 INFO: Alternative alignment: 1
- 17:10:00.531 INFO: 431 alignments done
- 17:10:00.532 INFO: Alternative alignment: 2
- 17:10:00.575 INFO: 54 alignments done
- 17:10:00.575 INFO: Alternative alignment: 3
- 17:10:00.585 INFO: 3 alignments done
- 17:10:00.606 INFO: Realigning 323 HMM-HMM alignments using Maximum Accuracy algorithm
- 17:10:02.588 INFO: 95 sequences belonging to 95 database HMMs found with an E-value < 0.001
- 17:10:02.589 INFO: Number of effective sequences of resulting query HMM: Neff = 6.62637
- 17:10:02.604 INFO: Iteration 2
- 17:10:02.902 INFO: Prefiltering database
- 17:11:34.781 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 944129
- 17:11:45.635 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 4643
- 17:11:45.635 INFO: HMMs passed 2nd prefilter and not found in previous iterations : 4551
- 17:11:45.635 INFO: Scoring 4551 HMMs using HMM-HMM Viterbi alignment
- 17:11:45.651 INFO: Alternative alignment: 0
- 17:12:04.352 INFO: 2000 alignments done
- 17:12:23.988 INFO: 4000 alignments done
- 17:12:29.328 INFO: 4551 alignments done
- 17:12:29.332 INFO: Alternative alignment: 1
- 17:12:33.809 INFO: 4508 alignments done
- 17:12:33.817 INFO: Alternative alignment: 2
- 17:12:34.623 INFO: 481 alignments done
- 17:12:34.624 INFO: Alternative alignment: 3
- 17:12:34.847 INFO: 76 alignments done
- 17:12:34.895 INFO: Rescoring previously found HMMs with Viterbi algorithm
- 17:12:34.913 INFO: Alternative alignment: 0
- 17:12:34.986 INFO: 92 alignments done
- 17:12:34.986 INFO: Alternative alignment: 1
- 17:12:35.069 INFO: 92 alignments done
- 17:12:35.069 INFO: Alternative alignment: 2
- 17:12:35.082 INFO: 9 alignments done
- 17:12:35.082 INFO: Alternative alignment: 3
- 17:12:35.092 INFO: 1 alignments done
- 17:12:35.140 INFO: Realigning 500 HMM-HMM alignments using Maximum Accuracy algorithm
- 17:12:39.055 INFO: 221 sequences belonging to 221 database HMMs found with an E-value < 0.001
- 17:12:39.057 INFO: Number of effective sequences of resulting query HMM: Neff = 7.29806
```

The docker command I'm running looks like this:
`docker run -v E:/data:/data soedinglab/hh-suite hhblits -i /data/input/$_  -oa3m /data/out/ -d /data/Dataset/uniref/UniRef30_2020_03`

Is there anything I can do to speed up this process?

**Comment by milot-mirdita** [comment]
We also have the `hhblits_omp` and `hhblits_mpi` (needs to be built from source) binaries to execute HHblits on a full ffindex database at once. You can use the `ffindex_build` binary to collect many separate files into a single database that can be given to either of these binaries. This will save some time but not a lot. Also make sure to set how many cpu cores HHblits is allowed to use.

If you dont actually require quite the sensitivity of HHblits you can use our other software package MMseqs2 that is many magnitudes faster.

**Comment by tueboesen** [comment]
So, the docker version that I'm running does not have omp or mpi I take it?
Does that mean that the option of specifying -cpu when running the docker version of hhblits does nothing?

`You can use the ffindex_build binary to collect many separate files into a single database that can be given to either of these binaries. This will save some time but not a lot. `
Could you elaborate on how this could save time? Or was that referring only to the previous comment about omp/mpi?

**Comment by milot-mirdita** [comment]
The container should contain the `_omp` binary.

Assuming you have a `/data/queries` folder with queries you want to process:
```
cd /data/queries
ffindex_build -s ../qdb.ffdata ../qdb.ffindex .
cd /data
hhblits_omp -i qdb -oa3m res_a3m -d /data/Dataset/uniref/UniRef30_2020_03 -cpu 16 ...
mkdir /data/results
ffindex_unpack res_a3m.ffdata res_a3m.ffindex /data/results
```

Now you should have one folder with all the result files in `/data/results`. This will save some overhead.

However the cost of HHblits's sensitivity is that it's not very fast. I would recommend to run it on some cluster or some distributed fashion or switch to MMseqs2 where annotating 25k sequences will take only minutes even on a Notebook. Then you could try to only annotate the sequences where MMseqs2 does not find any good hits with HHblits.

**Comment by tueboesen** [comment]
Ahh I see!
Thank you very much. I will try this approach

**Comment by rujpeng** [comment]
Dear HHsuite developers and users,

Related to this issue, I am using hhblits_omp to search many sequences (above 10,000) against custom database. The searching went well at the beginning. But the memory usage becomes higher and higher and the program gradually ended up with segmentation fault. I am wondering if you have the same situation or that I have not compiled HHsuite properly?

A typical output from my case was like following:
`slurm_script: line 8: 123689 Segmentation fault      hhblits_omp -cpu 4 -id 100 -maxfilt 30000 -diff 3000 -e 0.01 -cov 15 -qid 15 -i sleb -d ../searchMsa `

Best,
Junhui

**Comment by andrewcchang** [comment]
> The container should contain the `_omp` binary.
> 
> Assuming you have a `/data/queries` folder with queries you want to process:
> 
> ```
> cd /data/queries
> ffindex_build -s ../qdb.ffdata ../qdb.ffindex .
> cd /data
> hhblits_omp -i qdb -oa3m res_a3m -d /data/Dataset/uniref/UniRef30_2020_03 -cpu 16 ...
> mkdir /data/results
> ffindex_unpack res_a3m.ffdata res_a3m.ffindex /data/results
> ```
> 
> Now you should have one folder with all the result files in `/data/results`. This will save some overhead.
> 
> However the cost of HHblits's sensitivity is that it's not very fast. I would recommend to run it on some cluster or some distributed fashion or switch to MMseqs2 where annotating 25k sequences will take only minutes even on a Notebook. Then you could try to only annotate the sequences where MMseqs2 does not find any good hits with HHblits.

@milot-mirdita  Hello Milot,

I have similar problem where I am hoping to query 1M sequences agains Uniclust30 and get a3m files for each of the 1M sequences. Seems like `mmseqs` is the way to go, but I am not sure: 
1.  which function to use to get the a3m outputs just like `hhblits` or `hhblits_omp`, is it `mmseqs search`?
2.  how to use the downloaded Uniclust30 directly (xx_hhm.ffdata, xx_hhm.ffindex, xx_a3m.ffdata, xx_a3m.ffindex, xx_cs219.ffindex, xx_cs219.ffdata), or how to convert them to MMseqs2's db format?

Thank you so much for answering the question!

**Comment by qwe1997** [comment]
Hi,I am running HHblits for about 4000 protein sequences,however it takes about 4 minutes for each sequence.I want to speed up the process,so what should I do if I use MMseqs2 ?

**Comment by ksteczk** [comment]
HHblits scales up with CPUs very nicely - consider using more threads.
Also, check whether a disk where your query database is stored has good
read speeds. Of course, times depend also on how many iterations you run
etc.

śr., 4 sie 2021 o 06:15 qwe1997 ***@***.***> napisał(a):

**Comment by JustABiologist** [comment]
@qwe1997 if still relevant, I would recommend using a cluster, I ran it for about 69.000 sequences against uniclust30 with n=2, It took me 1.5 days using 8 512 GB RAM 256 Threads Nodes. First and foremost RAM is the limiting factor for this computation, depending on the size of  your target database. As each single threaded search for alignments has to access all the database. I think what happens is that hhblits loads the database slowly into RAM from disk if the query needs it. So to speed this up first option is to make a RAM disk and load the target database into a RAM disk or put it on a local SSD, as random access and IO will limit your performance if you read from HDD, but once this all is fixed, it's raw CPU thread count that improves speed. This all is intuition I gained from my first dip into this so take it with a grain of salt!

**Comment by swohlrab** [comment]
@JustABiologist I am having a similar task as yours (approx. 40.000 sequences against uniclust30) and I have access to a cluster. However the prefiltering database step task ages. Can you maybe provide me your (slurm?) script so that I could compare it to mine? That would help me a lot.

**Comment by pgmikhael** [comment]
Hi, 

Any solutions to the questions posed by @andrewcchang and @qwe1997 ?

**Comment by JustABiologist** [comment]
> @JustABiologist I am having a similar task as yours (approx. 40.000 sequences against uniclust30) and I have access to a cluster. However the prefiltering database step task ages. Can you maybe provide me your (slurm?) script so that I could compare it to mine? That would help me a lot.

Hey I would love to but it is in my old backup at my friends house. Will get back to you once he is back from vacation.

**Comment by milot-mirdita** [comment]
Normally, you'd use `hhblits_omp`, but its been broken since a while with a high number of threads.
we have the following script to parallelize hhblits:
https://github.com/soedinglab/hhdatabase_cif70/blob/master/pdb70_hhblits_lock.sh

The HHblits prefilter is just not very fast, but it helps if the database is fully within memory.
