### ISSUE TITLE
cstranslate questions [v3.0.0]

### ISSUE THREAD

**Issue by fslee62** [soedinglab/hh-suite#22]
hello,
i was using hhsuite2 with database files built by people before me. all was well. lately, i have been trying to update to version 3. i am able to make packed files from a3m's and hhm's using ffindex_build. however, i have trouble making the corresponding <db>_cs219 packed file and index using cstranslate.

(1) i used existing a3m's and hhm's (made from version 2) to make the <db>_cs219 ffdata and ffindex files and i got errors like:

Processing entry: 4jdv_L.a3m
Could not read entry: 4jdv_L.a3m, Message: Sequence 2 has 0 match columns but should have 103!

what may have gone wrong here? i also tried using freshly made a3m's and hhm's (from v3) to make the cs219 files. i saw similarly errors. perhaps these a3m's and hhm's were not prepared properly?

(2) do hhsuite v3 hhsearch and hhblits always require the corresponding cs219 db files to run? seemed so from my very limited experience with v3. i don't recall version 2 needing the cs219 files. simplistically speaking, what is being added here?

warm regards,
fred

**Comment by meiermark** [comment]
Hello,

(1) Do you want to do the cs219 files for version 3 with version 3?
     What was your command? Can you paste the corresponding entry of 4jdv_L.a3m?
(2) HHblits always needed the cs219 sequences for the prefilter. HHsearch needs the cs219 sequences now too, since we have rewritten the Viterbi algorithm, it was useful to sort the hhm's by the number of their match states. That is equal to the length of their cs219 sequences (equals the length of their entries in the cs219 ffindex). Otherwise we would have to preprocess the hhm's or a3m's in hhsearch.

**Comment by fslee62** [comment]
yes i like to build cs219 files for v3 using v3 tools.  are cs219 files from v2 and v3 cross-compatible?

i first used ffindex_build (v3) and existing a3m files (built by v2 tools) to make the corresponding <db>_a3m.ff{data,index}, which i then used to make the v3 cs219 files using cstranslate (v3):

${HHLIB}/bin/cstranslate -A ${HHLIB}/data/cs219.lib -D ${HHLIB}/data/context_data.lib \\
-x 0.3 -c 4 -f -i <db>_a3m -o <db>_cs219 -I a3m -b

$ more 4jdv_L.a3m
>4jdv_L
EIVLTQSPATLSLSPGERATLSCRASQSVSSYLAWYQQKPGQAPRLLIYDASNRATGIPARFSGSGSGTFTLTISSLEPEDFAVYYCQQYEFFGQGTKLEIK
>ss_pred
CCCEECCCCCCCCCCCCCEEEEEECCCCCCCCEEEEEECCCCCCEEEEEECCCCCCCCCCCCCCCCCCCEEEEECCCCCCCCEEEEEEECCCCCCCEEEEEC
>ss_conf
941650499201299995789997377932230321008999981268701556888889811153384168826899897556655314514892678859

**Comment by meiermark** [comment]
Oh, I see. cstranslate cannot handle secondary structure annotations.
I will look into this. Just for the calculation of the cs219 sequences you could
generate an a3m ffdatabase without these secondary structure annotations.

On a sidenote: As far as I see, you seem to have a3m's with just a single sequence. HHblits and HHsearch perform much better with multiple sequence alignments in the database. Those can be generated with hhblits. It is explained in the userguide.

**Comment by fslee62** [comment]
great markus. the moment i pasted the a3m file into the textbox, i also realized those a3m's i used were all just single sequences. yes MSA's will be much better for hhsuite.

okay i will remove the SS annotations and try again.
cheers,
fred

**Comment by meiermark** [comment]
In the recent commit, cstranslate should now work with a3m's that include secondary structure annotations.

**Comment by fslee62** [comment]
yes the new commit did allow me to use existing a3m files with secondary structure annotations. thank you very much.

**Comment by meiermark** [comment]
This issue can be closed, right?

**Comment by fslee62** [comment]
please do.
