### ISSUE TITLE
PDB70 license

### ISSUE THREAD

**Issue by Augustin-Zidek** [soedinglab/hh-suite#226]
The PDB70 database archive available at http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/ doesn't contain a license file and I wasn't able to find one anywhere in the [HH-suite User Guide](https://github.com/soedinglab/hh-suite/wiki).

Could you clarify what is the license for the PDB70 database (i.e. the data, not the scripts, that produce it)?

For comparison, BFD is CC BY-SA 4.0.

Thanks!

**Comment by martin-steinegger** [comment]
Oh indeed. We will add a Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) later today. Thank you for pointing it out.

**Comment by Augustin-Zidek** [comment]
Thank you very much!

**Comment by Augustin-Zidek** [comment]
Hi Martin, could you clarify where will you add the license? Will it be in the tar.gz with the database, in the User Guide, or somewhere else?

**Comment by martin-steinegger** [comment]
Ah I totally forgot. I have uploaded a license files CC BY-NC-SA 4.0. See https://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/LICENSE

**Comment by Augustin-Zidek** [comment]
Brilliant, thank you very much.
