### ISSUE TITLE
<db>_<a3m|hhm>.ffindex VERSUS <db>_<a3m|hhm>_db.index 

### ISSUE THREAD

**Issue by fslee62** [soedinglab/hh-suite#23]
hello,
i noticed that ffindex files and index files are almost the same but not identical. when i used ffindex_build (distributed with version 3), i actually made files identical to index files (and not the ffindex files). does it matter? are the 2 interchangeable? i thought v2 uses the index files and v3 uses the ffindex files.

also when the pfamA_29.0.tgz file downloaded from your server was untar-ed, i noticed something UNusual in this particular file: pfam_hhm.ffindex. it has "a3m" inside all over. was that intended?
best regards,
fred

**Comment by meiermark** [comment]
For version 3, we expect the same name for corresponding a3m, hhm, cs219 entries. In the case of the pfam all of them have the ".a3m" suffix.
In version 2, we expected a3m's to end with ".a3m", hhm's to end with ".hhm". That lead to suffix handling that was quite ugly in hhblits and if users wanted to build their own database with our nowadays parallelized tools (ffindex_apply_mpi, hhblits_omp, hhblits_mpi, cstranslate --ffindex, cstranslate_mpi), they had to fix the suffixes manually. So finally, we changed it to clean up code and make it easier for the users.

Additionally, we renamed the data and index files with the suffix ".ffindex" and "*.ffdata" to be more consistent. The content of the data-files are the same, the content of the index files differ in the suffixes of their entries.

I hope that explains a bit of the done changes.
In any case, if you have further questions, do not hesitate to ask them.

**Comment by fslee62** [comment]
thank you markus for the ultra-fast and generous support and help. it explained a lot.

it looked to me (when examining DB distributions from your server say pdb70) that the new ffindex files have NO suffixes whereas the older index files have suffixes. is that the correct understanding?

nevertheless, when i used ffindex_build (from version 3) to process the hhm's from scop70_1.75.hhm.tar.gz, i got a ffindex file that HAS suffixes. how come? 
fred

**Comment by meiermark** [comment]
For the pdb70, your observation is true.

The files unzipped by scop70_1.75.hhm.tar.gz have the ".hhm" suffix, so the entries in the ffindex generated by ffindex_build will also have the ".hmm" suffix. You can fix it with:
    sed -i "s/.hhm//" your_db_hhm.ffindex
for the corresponding a3m database you should do the same:
    sed -i "s/.a3m//" your_db_a3m.ffindex

**Comment by fslee62** [comment]
GOT IT. so it was not due to misuse of ffindex_build itself. that's all i need to know. thanks much again.

**Comment by fslee62** [comment]
sorry for sticking with this issue. i did a quick test. it seemed like hhsearch and hhblits do NOT care whether or not the ffindex files have the .a3m or .hhm suffixes inside. is this observation generally true?

**Comment by meiermark** [comment]
Well, kind of. The hhm's will improve the speed of hhblits, since they are precalculated from a3m's. If corresponding entries in the different databases have different names, then hhblits won't be able to find the precalculated hhm to an a3m. In this case, hhblits will use the a3m.

However, the a3m's and the cs219's need to have the same names in their entries for HHblits to work properly.
