### ISSUE TITLE
PDB70 archive

### ISSUE THREAD

**Issue by mhj112358** [soedinglab/hh-suite#231]
Hi guys, 

Does anyone know if there is anywhere I could get an older version of PDB70 hhm database (pre-CASP 14, ie., Apr-2020 etc) or if anyone would be kind to provide a copy? Thanks in advance.

**Comment by milot-mirdita** [comment]
I am trying to fetch the old release from our tape archive. If it works successfully you will find the `pdb70_from_mmcif_200401.tar.gz` at http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/old-releases/ soon. I'll update you once it finished.

**Comment by mhj112358** [comment]
Dear Milot,

Thank you so much for your kind help :) Just a small question, when I tried
to download the 0401 database it says "You don't have permission to access
this resource" but I could access other files in the hhsuite-dbs directory
without any problem. May I know how I could get around this please? Thanks
again and wish you a great week ahead.

**Comment by milot-mirdita** [comment]
We have some problem with the tape archive, it still didn't copy the file. Trying to find out what's wrong.

**Comment by milot-mirdita** [comment]
Could you try now? It should have been successfully copied.

**Comment by mhj112358** [comment]
Hi Milot, thanks a lot. I am downloading it just fine 👍
