### ISSUE TITLE
name of target hit didn't show up in -blasttab output

### ISSUE THREAD

**Issue by jhpanda** [soedinglab/hh-suite#232]
Hi hh-suite users and developers,

I wanted a blast m8 format output with -blasttab, and I was expecting that the second column should be the name of target hits, as described below
                  1      2      3           4         5        6      8    9      10   11   12
                  'query target #match/tLen #mismatch #gapOpen qstart qend tstart tend eval score'

But the output is the index of target hits in targetDB? Example is shown below:
XP_033246917.1  72855   1.000   383 0   0   1   383 1   383 8.54E-92    493.2

I used the following sequence for input, and run: 
hhblits -i test.fasta -o test.hhr -d UniRef30_2020_06 -blasttab test.m8

>XP_033246917.1
MLAETNIFTIESKRDYLTGKISKNLIHGKSTPLNTLSKSHKRKHRLLSTVDRAIQVSQKHLIPFSPIRTSTSKKFNILNIHKSTNINLSNHNKNTTPTIVFHQLFHSIKSALPKHNFLYTDGSKAGGITSYCITNESAVIKTGLLPTYSSVLSSEIIAIHEAILFTRYKRGKYAICTDSLSSITSIRNPNNHSYYASSIRNLLSTHFPKILIIWIPSHIGIKGNEFADSTARMNAKFPLIYTPNHNSTDIAHFLKKILQSKQTDLLTNTSTWYQQISNLATNNTPKNNILNRRHQVIFNRLRLGHTKLTNAHYIDKTLPNTCPLCHNANIDLRHTLYTCPSLLPQRSLSFNNNDPMQLIANPTNSNSKIILKFLQTANILHNIX

Do I need extra scripts to generate a new output or am I missing anything?

Thanks,
Junhui

**Comment by milot-mirdita** [comment]
You are right that is kind of inconvenient. This issue was reported previously (https://github.com/soedinglab/hh-suite/pull/68). I merged that PR. You will have to compile HHsuite from source for now, but this will be part of the next release when we make one.
