### ISSUE TITLE
HHpred in hh-suite 3 declares Modeller 9.13 as dependency, could be Modeller 9.17

### ISSUE THREAD

**Issue by lukaszimmermann** [soedinglab/hh-suite#24]
hh-suite 3.0.0 (15-03-2015)

The Bioinformatics Toolkit 
https://toolkit.tuebingen.mpg.de/common/tool_versions
uses HHpred in conjunction with Modeller 9.17 without problems. Maybe the dependency on Modeller, as declared in the Makefile of HHpred, should also be increased to Modeller 9.17.

**Comment by meiermark** [comment]
Will look into it next week.

Am 11.11.2016 13:28 schrieb "lkszmn" <notifications@github.com>:

**Comment by meiermark** [comment]
opened a project for this purpose...
might need more checking
