### ISSUE TITLE
Conda installation of hhsuite not working

### ISSUE THREAD

**Issue by luederm** [soedinglab/hh-suite#242]
I am not sure where the best place to post this is, however I am currently unable to install hhsuite from conda. 

Command:
`conda install -c bioconda hhsuite`

Output:
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: | 
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed                                                                                                                                                                                 
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versions

It is strange the there is no output after the last line. Maybe there is a bug in the repodata package specification.

I tested on mac with conda version 4.8.4 and linux with conda version 4.9.2.

**Comment by milot-mirdita** [comment]
You probably also need to specify `-c conda-forge` or make sure they are both among your conda default channels.

**Comment by luederm** [comment]
@milot-mirdita That worked. Thanks! 

Perhaps the command listed at https://anaconda.org/bioconda/hhsuite could be updated to include conda-forge?
