### ISSUE TITLE
Can I use hh-suite in natural language processing scenario?

### ISSUE THREAD

**Issue by thuxugang** [soedinglab/hh-suite#248]
Hi, thanks for the great work! 
I was wodering if  I can inroduce hh-suite directly into natural language processing scenario. I plan to build a database with all 26 characters and find the most similar sentences by hhsearch. Is it a feasible plan? Did hh-suite has something specifically for protein sequence such as BLOSUM or PAM matrixs?

**Comment by milot-mirdita** [comment]
This would probably be too difficult as too many assumptions about proteins are backed into the HH-suite.

If you really want to pursue the idea of using a bioinformatics sequence search method for NLP, you would probably have an easier time modifying our other sequence search package MMseqs2 (https://github.com/soedinglab/mmseqs2) for this purpose.

**Comment by thuxugang** [comment]
Thanks!
