### ISSUE TITLE
scop70_1.75_cs219.ffdata missing?

### ISSUE THREAD

**Issue by sowani** [soedinglab/hh-suite#25]
Hi,

I am testing the hh-suite on ppc64le. I downloaded following databases before I begun testing.
From http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/ :
pdb70_14Sep16.tgz
pfamA_29.0.tgz
uniprot20_2016_02.tgz
From http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsearch_dbs/ :
scop70_1.75.a3m.tar.gz
scop70_1.75.hhm.tar.gz

I extracted these databases to their appropriate locations, so that I could just copy-paste test commands from User Guide and execute them. Also I have set all the recommended environment variables and paths as per User Guide. However, the very first command "hhsearch -cpu 4 -i data/query.a3m -d dbs/scop70_1.75 -o data/query.hhr" gives me following error:
- 18:22:32.998 ERROR: In /root/hh-suite/src/hhdatabase.cpp:35: FFindexDatabase:
- 18:22:32.998 ERROR:   could not open file 'dbs/scop70_1.75_cs219.ffdata'

I checked for the presence of scop70_1.75_cs219.ffdata file everywhere, but it is missing. User Guide section 2.4 on page 8 mentions that _cs219.ffdata is one of the eight files a database consists of. However this file seems to be missing.

Am I working with correct databases? Do I have to install something additional? Or do I have to "condition" existing database files to generate these kinds of files?

Thanks,
Atul.

**Comment by meiermark** [comment]
Hi. You are using the wrong database. Take the hhsuite database. Since
hhsuite 3.0 hhsearch requires the same database as hhblits. Hope that helps
you.

Am 11.11.2016 14:02 schrieb "sowani" <notifications@github.com>:

**Comment by milot-mirdita** [comment]
Hi Atul,

Sorry for the confusion. We were not providing the SCOP70 database in a format that could be used by HH-suite version 3. I just uploaded an archive with a complete SCOP70 database (including cs219). Do note however that this cs219 is not compatible to old HH-suite versions, that would need a bit more work. (Write me if you need it, I could generate it.)

You can find the database [here](http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/scop70_1.75_hhsuite3.tar.gz).

Best regards,
Milot

**Comment by sowani** [comment]
Thanks for updating the database! I am downloading the new DB file and I will update soon once I complete the download and extract the DB files.

**Comment by sowani** [comment]
Update on the new scop70_1.75 database: I could successfully run the first hhsearch command given in the User Guide with this database. Many thanks to @milot-mirdita ! :)

I am closing this issue as the original problem got resolved. Here is the output I received (whether this is accurate or not is another topic).
root@pts00433-vm12:~/hh-suite# hhsearch -cpu 4 -i data/query.a3m -d dbs/scop70_1.75 -o data/query.hhr
- 17:25:30.890 INFO: data/query.a3m is in A2M, A3M or FASTA format
- 17:25:30.951 INFO: Searching 13730 database HHMs without prefiltering
- 17:25:30.959 INFO: Iteration 1
- 17:25:31.306 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 13730
- 17:25:31.307 INFO: HMMs passed 2nd prefilter and not found in previous iterations : 13730
- 17:25:31.307 INFO: Scoring 13730 HMMs using HMM-HMM Viterbi alignment
- 17:25:31.411 INFO: Alternative alignment: 0
- 17:26:59.299 INFO: 13730 alignments done
- 17:26:59.310 INFO: Alternative alignment: 1
- 17:26:59.310 INFO: Alternative alignment: 2
- 17:26:59.310 INFO: Alternative alignment: 3
- 17:26:59.450 INFO: Realigning 10 HMM-HMM alignments using Maximum Accuracy algorithm
- 17:26:59.770 INFO: 0 sequences belonging to 0 database HMMs found with an E-value < 0.001

Query         sp|Q5VUD6|FA69B_HUMAN Protein FAM69B OS=Homo sapiens GN=FAM69B PE=2 SV=3
Match_columns 431
No_of_seqs    59 out of 59
Neff          4.27431
Searched_HMMs 13730
Date          Mon Nov 14 17:26:59 2016
Command       hhsearch -cpu 4 -i data/query.a3m -d dbs/scop70_1.75 -o data/query.hhr

 No Hit                             Prob E-value P-value  Score    SS Cols Query HMM  Template HMM
  1 d1muka_ e.8.1.4 (A:) Reovirus    0.0 1.4E+04       1 -127.0   0.0   14  188-201   746-759 (1264)
  2 d1u6gc_ a.118.1.2 (C:) Cullin-   0.0 1.4E+04       1 -127.0   0.0    1    1-1       1-1   (1207)
  3 d1jrob2 d.133.1.1 (B:124-777)    0.0 1.4E+04       1 -127.0   0.0   12  154-165   231-242 (654)
  4 d1ffvb2 d.133.1.1 (B:147-803)    0.0 1.4E+04       1 -127.0   0.0   15  154-168   251-265 (657)
  5 d1bjta_ e.11.1.1 (A:) DNA topo   0.0 1.4E+04       1 -127.0   0.0   32  192-230   284-315 (760)
  6 d1twfa_ e.29.1.2 (A:) RBP1 {Ba   0.0 1.4E+04       1 -127.0   0.0    4   35-38    570-573 (1449)
  7 d1w7ca1 b.30.2.1 (A:316-775) L   0.0 1.4E+04       1 -127.0   0.0   14  105-118   144-157 (460)
  8 d1by5a_ f.4.3.3 (A:) Ferric hy   0.0 1.4E+04       1 -127.0   0.0    1   25-25     57-57  (697)
  9 d1dmta_ d.92.1.4 (A:) Neutral    0.0 1.4E+04       1 -127.0   0.0    3   92-94     87-89  (696)
 10 d2i3oa1 d.153.1.6 (A:1-516) Hy   0.0 1.4E+04       1 -127.0   0.0    1  279-279   264-264 (516)

**Comment by yazhinia** [comment]
I have downloaded uniprot20_2016_02.tgz. While running miprun to build a3m format database, I get the same error: 'could not open file '/dir/_cs219.ffdata. Also in my usr/bin folder, ffindex_apply_mpi is not found. I can see only ffinidex_apply_mpi.c  in hh-suite/lib/ffindex/src/ folder. Is ffindex_apply and ffindex_apply_mpi is same?. I don't know whether export path problem or installation problem in ffinder_apply_mpi.
Please help me to resolve this.

**Comment by croth1** [comment]
@yazhinia, can you please open a new issue and add a link to the discussion here? That way it is much easier for us keeping track and handling of your issue.

**Comment by yazhinia** [comment]
Here is the link: https://github.com/soedinglab/hh-suite/issues/65
