### ISSUE TITLE
BFD a3m issue

### ISSUE THREAD

**Issue by mhj112358** [soedinglab/hh-suite#251]
Hi guys, 

I am working on constructing multiple sequence alignments by HHblits-ing through the BFD database. However, when I try to unpack tar.gz file I downloaded from https://bfd.mmseqs.com, I have 13T disk space available but always get the following error:

tar: bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_a3m.ffdata: Wrote only 4608 of 10240 bytes

Have you guys encountered this and any suggestions on how to resolve it? 

Thanks a lot.

**Comment by milot-mirdita** [comment]
I added both an MD5 hash and the final size in byte to the download page. Could you please check if they match? If they don't match please try to download with `aria2c` instead of `wget` or `curl`. We have had good experiences with that tool and downloading large databases such as the BFD.

**Comment by mhj112358** [comment]
Thank you very much for your kind reply. After a thorough system check, I've found out the cause to be my hard disk being damaged and now it is working properly. I'll close this issue now :)
