### ISSUE TITLE
[hhmake] -add_cons results in seq fault

### ISSUE THREAD

**Issue by ksteczk** [soedinglab/hh-suite#252]
hhmake with option -add_cons results in seqfault, e.g.

`ffindex_get pfam_a3m_oryg.ffdata pfam_a3m_oryg.ffindex PF00045.21|hhmake -i stdin -o stdout -neff 10 -add_cons
`
output:
> - 11:38:52.765 INFO: Reading HMM / multiple alignment from standard input ...
> 
> Segmentation fault
> 

a3m files come from pfam 34 db from hh db repo.
Without -add_cons it runs smoothly.

**Comment by milot-mirdita** [comment]
Did it work before? From What I can see combining Neff >= 0.999 and -add_cons should have basically always crashed. Not sure what the right fix is. Maybe ignoring -add_cons in hhmake completely as it prints the consensus sequence always anyway?

**Comment by ksteczk** [comment]
I just wanted to have a nice consensus sequence in the profile (not uniprot representative). The default consensus sequence is full of x'es and marks only the conserved residues. But I can live without that.

**Comment by ghbillings** [comment]
I'm hoping to re-open this; I'm running into what I assume is the same issue--I'm consistently getting segfaults when running hhblits with the  `-add_cons` option.  Not using `-add_cons` is a fine solution for us, but I'm hoping to save others the time it takes to figure out what's causing the segfaults.
