### ISSUE TITLE
Pairwise MSA with hhalign

### ISSUE THREAD

**Issue by LeonardoMorenoG** [soedinglab/hh-suite#257]
## Context
I am trying to use hhalign to do a pairwise alignment of two MSA using the following command:
hhalign -M 50 -t ma1.fasta -M 50 -i clustersAlignments/cluster_114.muscle.fasta -o ma2.hhr -Ofas ma2.fasta -hide_cons -glob
## Expected Behavior
I expected that my output fasta included  5 sequences (2 from the file ma1.faa and 3 from the file cluster_114.muscle.fasta)

## Current Behavior
Instead, the output fasta file only includes 2 sequences (1 from each file)

## Question
Am I wrong when I expect as output a MSA with 5 sequences?

**Comment by milot-mirdita** [comment]
You have to call `hhalign` with `-oa3m` and use `reformat.pl` to get a non-pairwise FASTA file.
If you compile from source, `hhalign` recently learned the `-all` flag to also get the unfiltered output with all sequences, otherwise you will only get a filtered MSA from `hhalign`.

**Comment by LeonardoMorenoG** [comment]
Thanks for the information. It worked perfectly. I'll close the issue

**Comment by alephreish** [comment]
@milot-mirdita The new `-all` flag is a very important addition. (BTW I tried to mark all sequences with `@` and use the `-mark` flag, but it is simply ignored.) Is there a time frame for the next release? The version available via conda doesn't have a way to preserve all the sequence.
