### ISSUE TITLE
Is it possible to reconstruct .a3m with .hhm

### ISSUE THREAD

**Issue by xptree** [soedinglab/hh-suite#266]
Dear authors,

We are running a bunch of `hhblits` jobs for MSA. However, we are unable to store all .a3m files due to disk space limit. We found that .hhm file could be much smaller than the .a3m file. We wonder if it is possible to reconstruct .a3m with .hhm (e.g., by `hhalign` and/or `hhsearch`).

Thanks in advance!

**Comment by milot-mirdita** [comment]
No, the conversion to hhm loses a lot of information that cannot be recovered anymore.

You could instead use `hhfilter` to thin down the a3ms by removing redundant sequences, if you are that space limited.

**Comment by xptree** [comment]
Thanks, @milot-mirdita
