### ISSUE TITLE
compile error in macos BigSur 11.2.3 

### ISSUE THREAD

**Issue by 2efPer** [soedinglab/hh-suite#269]
:exclamation: Make to check out our [User Guide](https://github.com/soedinglab/hh-suite/wiki).

## Current Behavior
Here is my error log:  https://gist.github.com/2efPer/91076605e1a7b55b52fb513533582f9b

## Your Environment
macos BigSur 11.2.3 
gcc10

**Comment by milot-mirdita** [comment]
Could you post all commands you used to compile and how you installed cmake/gcc (homebrew?).

I just tried it on a Mac Mini M1 with Big Sur. Clang compiled without issues and GCC had a minor ARM issue that I just fixed, however that looks completely different to your issue.

**Comment by 2efPer** [comment]
> Could you post all commands you used to compile and how you installed cmake/gcc (homebrew?).
> 
> I just tried it on a Mac Mini M1 with Big Sur. Clang compiled without issues and GCC had a minor ARM issue that I just fixed, however that looks completely different to your issue.

I just find out my CMakeLists.txt has been changed because of my early compiler problem, some extra header directory confused the compiler. It is completely fine when I remove those headers' directory.Thanks for you time, I think I better close this issue.
