### ISSUE TITLE
In hh-suite 3, hhalign does not longer seem to produce dotplots

### ISSUE THREAD

**Issue by lkszmn** [soedinglab/hh-suite#27]
hh-suite 3

In hh-suite 3, hhalign does not longer seem to produce dotplots. The user-guide
claims otherwise.

**Comment by meiermark** [comment]
True. That option is no longer available. I will update the userguide on
Monday.

Am 12.11.2016 13:30 schrieb "lkszmn" <notifications@github.com>:
