### ISSUE TITLE
unzip error for uniclust30_2018_08_hhsuite.tar.gz

### ISSUE THREAD

**Issue by wtzhao1631** [soedinglab/hh-suite#271]
After downloading the database: uniclust30_2018_08_hhsuite,  I meet the following error when unzipping the file.

$ tar xzvf uniclust30_2018_08_hhsuite.tar.gz

uniclust30_2018_08/uniclust30_2018_08_a3m.ffdata
uniclust30_2018_08/uniclust30_2018_08_a3m.ffindex
uniclust30_2018_08/uniclust30_2018_08_hhm.ffdata
uniclust30_2018_08/uniclust30_2018_08_hhm.ffindex
uniclust30_2018_08/uniclust30_2018_08_cs219.ffdata
uniclust30_2018_08/uniclust30_2018_08_cs219.ffindex
uniclust30_2018_08/uniclust30_2018_08.cs219
uniclust30_2018_08/uniclust30_2018_08.cs219.sizes
uniclust30_2018_08/uniclust30_2018_08_a3m_db
tar: uniclust30_2018_08/uniclust30_2018_08_a3m_db: Cannot create symlink to 'uniclust30_2018_08_a3m.ffdata': Operation not supported
uniclust30_2018_08/uniclust30_2018_08_a3m_db.index
uniclust30_2018_08/uniclust30_2018_08_hhm_db
tar: uniclust30_2018_08/uniclust30_2018_08_hhm_db: Cannot create symlink to 'uniclust30_2018_08_hhm.ffdata': Operation not supported
uniclust30_2018_08/uniclust30_2018_08_hhm_db.index
uniclust30_2018_08/uniclust30_2018_08_md5sum
tar: Exiting with failure status due to previous errors

**Comment by milot-mirdita** [comment]
What tar are you using? Please try if extracting works with gnu tar.
