### ISSUE TITLE
[HHblits] The output first sequence length(32763) is not equal to query sequence length(34350)

### ISSUE THREAD

**Issue by Licko0909** [soedinglab/hh-suite#278]
## Current Behavior
**1) [HHblits] The output first sequence length is not equal to query sequence length.**
![image](https://user-images.githubusercontent.com/27897166/126601695-055e132a-332f-49be-9a0c-1b80b9c916d5.png)
**2) and many MSAs seqence have many gap likes ‘----’.**
![image](https://user-images.githubusercontent.com/27897166/126602347-b224be40-64cf-4a87-97c5-3b8a1e0c1071.png)
![image](https://user-images.githubusercontent.com/27897166/126602444-1aeeb27d-151e-43f4-a9a7-962d8969c86a.png)

## Steps to Reproduce (for bugs)
---Command line Command execution: 
`hhblits -i uc031rqd.1.seq -cpu 16 -n 1 -d /data/hh-suite/UniRef30_2020_06_hhsuite/UniRef30_2020_06 -oa3m uc031rqd.1.a3m -maxres 35000`

## HH-suite Output (for bugs)
Not any error mentioned and I can get the output file.
![image](https://user-images.githubusercontent.com/27897166/126602466-a68426b0-f5a5-4c10-84f9-fdeeec79543e.png)

## Context and Environment
---sequence file:
[uc031rqd.1.seq in here](https://www.uniprot.org/uniprot/Q8WZ42.fasta)

---Versison: 
HH-suite version = 3.3.0

---Server:
System: Ubuntu 18.04
Memory: 504G
![image](https://user-images.githubusercontent.com/27897166/126603450-a22554d0-602f-4dc0-9487-824bfd4dc32b.png)

**Comment by milot-mirdita** [comment]
That looks pretty much like expected. There are two things to keep in mind:
1) HHblits is a local aligner, so its likely that only sequence chunks will be aligned to the query (You can lower the `-mact` parameter to get more global, but less precise alignments. See https://github.com/soedinglab/hh-suite/wiki#what-does-the-maximum-accuracy-alignment-algorithm-do)
2) The default output format is not aligned FASTA but a3m. See a description here: https://github.com/soedinglab/hh-suite/wiki#multiple-sequence-alignment-formats. A3M saves a lot of space by placing a lower case letter in case of an insert state and omitting gaps in other sequences. You can write results in standard aligned FASTA with `-Ofas` or use the `reformat.pl` script to convert them between formats.
