### ISSUE TITLE
Illegal instruction running on AMD, compiled on INTEL

### ISSUE THREAD

**Issue by chrisroat** [soedinglab/hh-suite#282]
I am compiling via the [AlphaFold Dockerfile](https://github.com/deepmind/alphafold/blob/b88f8dacef5d94e4d3d49613d08523feb20caec1/docker/Dockerfile#L36) on an Intel machine, and deploying (after converting to a Singularity container) on a cluster containing both AMD and Intel CPUs.  

When simply running `hhsearch` with no parameters, I get an "Illegal instruction" failure on the AMD CPUs, but not the Intel CPUs.  From past Issues, I gather this is often because of instruction set mismatch.  My Intel CPU flags also list avx512{f,dq,cd,bw,vl}, but the AMD flags do not.  Would this be a problem, and if so, can those be turned off?  If that is not the issue, what are other avenues to explore?

For reference, my host:

model name      : Intel(R) Xeon(R) W-2195 CPU @ 2.30GHz
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req md_clear flush_l1d

For reference, an AMD host:

model name      : AMD EPYC 7502P 32-Core Processor
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb cat_l3 cdp_l3 hw_pstate sme retpoline_amd ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip overflow_recov succor smca

**Comment by milot-mirdita** [comment]
Please add `-DHAVE_AVX2=1` to the cmake call in the Dockerfile. By default we compile with `-march=native` meaning it will use AVX-512 on your Intel CPU. Setting the parameter will make it use up to AVX2 only.

**Comment by chrisroat** [comment]
Perfect.  Thank you.
