### ISSUE TITLE
Problem of hhsuite run time

### ISSUE THREAD

**Issue by NikoBelice** [soedinglab/hh-suite#289]
Hello all

I am now using WSL2 to run RoseTTAFold. The first step of RoseTTAFold is using hhsuite. However, the runtime of the hhsuite was very long. It took me 12h to run in the first time. After first time, it still need more than 8h to run. Due to the core dumped problem, I used compiled hhsuite-3.30 in RoseTTAFold.

The setting of my computer is 48 logical processors, 24 cores, 128g memory, CPU supports AVX2 and SSE2. The operation of my system is Win10.

I think this setting will not take me lots of time to run the hhuite. When running hhuite, I noticed that the usage of CPU and GPU are too low, it could say did not use them to run. So, I am curious for how can I increase the usage of the CPU or GPU. Because the Uniref30 and BFD databases are too large, I used the external hard drive to store the databases. I am not sure whether the reading speed of the hard drive affects the CPU to process the data.

Since I am the beginner of the coding, I did not modified the code, the only place I changed was the CPU and MEM values. I changed them to 48 and 128.

The code relates to hhsuite in RoseTTAFold:
run file calls the make_mas file to execute the hhsuite
![run](https://user-images.githubusercontent.com/69826122/132951796-b432f4ec-3456-44dc-aafb-51a138efa8f1.png)
![make_msa](https://user-images.githubusercontent.com/69826122/132951803-eafbd0c8-ac2c-4220-848d-ff6c06b6fdbe.png)

I appreciate any suggestions.
Thanks all!

**Comment by jarunan** [comment]
Hi there,

Do you have an update regarding this issue?

I am facing a similar issue. I have install hhsuite for AlphaFold. I observed that hhsearch and hhblits did not use GPU and hhblits used only <10% of one CPU. With the sample T1050.fasta, the compuational stayed with hhblits for 4 hours (our current max runtime) without completion.

Best regards,
Jarunan

**Comment by ksteczk** [comment]
Check your system storage load. It might be a slow database readout which
causes insufficient CPU usage.

Also, hhsuite does not use GPU - it is already highly optimized for the CPU
(really, it is very fast), but is highly dependent on disks performance.


pt., 19 lis 2021 o 09:33 jarunan ***@***.***> napisał(a):

**Comment by jarunan** [comment]
Hi Kamil,

Thanks for the hint. I will check the storage out.

Best,
Jarunan

**Comment by NikoBelice** [comment]
Hi,

Maybe you can try to use an external SSD to increase the speed of data transmission. It worked for me.

Best
________________________________
发件人: jarunan ***@***.***>
发送时间: 2021年11月19日 4:42
收件人: soedinglab/hh-suite ***@***.***>
抄送: Liang, Tianjian ***@***.***>; Author ***@***.***>
主题: Re: [soedinglab/hh-suite] Problem of hhsuite run time (#289)


Hi Kamil,

Thanks for the hint. I will check the storage out.

Best,
Jarunan

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsoedinglab%2Fhh-suite%2Fissues%2F289%23issuecomment-973912008&data=04%7C01%7Ctil60%40pitt.edu%7C40d8b113a1344cca84f108d9ab40e920%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637729117552899321%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LscIgwg73BNTUB0SGLlLaYNjoHs1gi%2Bb3SjJJh6aRk4%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQUXMSSDI3GB4LSRL4O2F4DUMYLYPANCNFSM5D3BC7LA&data=04%7C01%7Ctil60%40pitt.edu%7C40d8b113a1344cca84f108d9ab40e920%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637729117552909308%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=S4UWw92uj3hXkz8oEC6JCimI%2BfDOJBWhiDa9P6C%2BeHs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctil60%40pitt.edu%7C40d8b113a1344cca84f108d9ab40e920%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637729117552919305%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VreFoMNdSjiiS9KLst%2FYuZykkG0%2BkGYfkQ74gx99hwc%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ctil60%40pitt.edu%7C40d8b113a1344cca84f108d9ab40e920%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637729117552919305%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tQHYi%2B7axmVdwpLNOADLI0%2Ft8snLx5ghLOjAO0mdRv8%3D&reserved=0>.
