### ISSUE TITLE
hhsearch can not open file 'pdb70/pdb70_cs219.ffdata'

### ISSUE THREAD

**Issue by XiaoTigerHAO** [soedinglab/hh-suite#290]
Hi,

I use conda created a virtual enviroument for running hhsearch on ubuntu 20.04.

The cmd like this: 
hhsearch -i /tmp/123456/query.a3m -o /tmp/123456/output.hhr -maxseq 1000000 -d /public/AlphaFoldDB/pdb70/pdb70

while i got an error shown like this:
ERROR: In /opt/conda/conda-bld/hhsuite_1616660820288/work/src/ffindexdatabase.cpp:11: FFindexDatabase:
ERROR: 	could not open file '/public/AlphaFoldDB/pdb70/pdb70_cs219.ffdata'

I have re-downloaded the latest dataset several times.

the error always occurs.

Please help on this.

Thanks a lot.

best,
user
Sep 24, 2021

**Comment by DominicLogel** [comment]
Hello, I have this same issue. How were you able to solve this?

**Comment by wdnmd80** [comment]
Maybe database is not readable, try sudo chmod a=rwx /public/AlphaFoldDB/pdb70/*
