### ISSUE TITLE
Is it currently supported to read database in ceph？

### ISSUE THREAD

**Issue by onlyonewater** [soedinglab/hh-suite#316]
hi, due to the memory on the server, I have to put the database into aws ceph, so does the current code support reading the database from ceph?

**Comment by milot-mirdita** [comment]
We never used Ceph. Did you get it to work?

**Comment by milot-mirdita** [comment]
By the way, if you use any network attach storage. We recommend to keep the `cs219` files on a fast local disk.

```
cd FAST_LOCAL_DISK
for i in a3m hhm; do
ln -s path-to-nfs/db_${i}.ffdata 
ln -s path-to-nfs/db_${i}.ffindex
done
cp path-to-nfs/db_cs219.ff{data,index} .
hhblits -d path-to-nfs/db ...
```
