### ISSUE TITLE
Query: 2 new files seen in source code.

### ISSUE THREAD

**Issue by sowani** [soedinglab/hh-suite#32]
Hi, I have been working on hhsuite source code for some time so my version of source code is slightly older (I think more than a month or so). I cloned hhsuite yesterday as I wanted to have a local reference copy. While comparing the files I found that there are 2 new files in the current codebase:
src/hhblits_mpi.cpp
lib/ffindex/src/ffindex_from_fasta_with_split.c

I did not see anything related to this in the CHANGES file either. The version strings (in top level CMakeLists.txt) are same in both code bases. Are these 2 new files essential for hhsuite or they are just kind of utilities which are not necessary for core functioning of hh-suite?

Thanks,
Atul.

**Comment by milot-mirdita** [comment]
Hi Atul,

The two files build an utility executable "hhblits_mpi" that replaces the usual "ffindex_apply_mpi ... -- hhblits ..." calls, this lowers the overhead by quite a bit, when you start hhblits searches for many thousand small query sequences.

But they are not related to the core search functionality.

Best,
Milot

**Comment by sowani** [comment]
Thanks @milot-mirdita for the explanation. So I will defer checking these files for my current porting work. Once I am done with immediate high priority tasks (like fixing crashes in ported code etc.) I will have a look at these files.
I am closing this issue now.

Mit freundlichen Grüßen/Best regards,
Atul
