### ISSUE TITLE
Issue with make & install

### ISSUE THREAD

**Issue by ndmaduro** [soedinglab/hh-suite#328]
:exclamation: Make to check out our [User Guide](https://github.com/soedinglab/hh-suite/wiki).

## Expected Behavior
make & install hh-suite
## Current Behavior
error in make on iOS 13.0
## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps.

## HH-suite Output (for bugs)
Please make sure to post the complete output of the tool you called. Please use [gist.github.com](https://gist.github.com).
build % sudo make -j 4 && make install                    
[  3%] Built target ffindex
[  6%] Built target generated
[ 13%] Built target CS_OBJECTS
[ 15%] Built target mpq
[ 17%] Built target hhviterbialgorithm_with_celloff_and_ss
[ 19%] Built target hhviterbialgorithm_and_ss
[ 21%] Built target hhviterbialgorithm_with_celloff
[ 22%] Built target A3M_COMPRESS
[ 26%] Built target ffindex_unpack
[ 26%] Built target ffindex_order
[ 28%] Built target ffindex_modify
[ 30%] Built target ffindex_get
[ 34%] Built target ffindex_reduce
[ 35%] Built target ffindex_from_fasta_with_split
[ 36%] Built target ffindex_build
[ 36%] Built target ffindex_from_fasta
[ 40%] Built target ffindex_apply
[ 40%] Built target a3m_database_reduce
[ 41%] Built target ffindex_apply_mpi
[ 68%] Built target HH_OBJECTS
[ 72%] Built target a3m_database_extract
[ 72%] Built target a3m_reduce
[ 72%] Built target a3m_database_filter
[ 74%] Built target a3m_extract
[ 74%] Linking CXX executable hhfilter
[ 76%] Linking CXX executable hhmake
[ 76%] Linking CXX executable hhblits
[ 77%] Linking CXX executable hhalign_omp
0  0x106711ffa  __assert_rtn + 139
1  0x10654528d  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 4989
2  0x106535f8f  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 207
3  0x106583404  archive::File<x86_64>::makeObjectFileForMember(archive::File<x86_64>::Entry const*) const + 1268
4  0x106582a8b  archive::File<x86_64>::File(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, archive::ParserOptions const&) + 1035
5  0x106581c72  archive::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, archive::ParserOptions const&) + 146
6  0x1065acc8e  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 2734
7  0x1065affa0  ___ZN2ld4tool10InputFilesC2ER7Options_block_invoke + 48
8  0x7ff80acd7a77  _dispatch_client_callout2 + 8
9  0x7ff80ace94e1  _dispatch_apply_invoke + 213
10  0x7ff80acd7a44  _dispatch_client_callout + 8
11  0x7ff80ace77f6  _dispatch_root_queue_drain + 683
12  0x7ff80ace7e4d  _dispatch_worker_thread2 + 160
13  0x7ff80ae53c9d  _pthread_wqthread + 256
A linker snapshot was created at:
	/tmp/hhfilter-2022-10-24-231407.ld-snapshot
ld: Assertion failed: (_file->_atomsArrayCount == computedAtomCount && "more atoms allocated than expected"), function parse, file macho_relocatable_file.cpp, line 2061.
0  0x105f19ffa  __assert_rtn + 139
0  0x10e543ffa  __assert_rtn + 139
1  0x105d4d28d  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 4989
1  0x10e37728d  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 4989
2  0x105d3df8f  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 207
2  0x10e367f8f  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 207
3  0x105d8b404  archive::File<x86_64>::makeObjectFileForMember(archive::File<x86_64>::Entry const*) const + 1268
3  0x10e3b5404  archive::File<x86_64>::makeObjectFileForMember(archive::File<x86_64>::Entry const*) const + 1268
4  0x105d8aa8b  archive::File<x86_64>::File(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, archive::ParserOptions const&) + 1035
4  0x10e3b4a8b  archive::File<x86_64>::File(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, archive::ParserOptions const&) + 1035
5  0x105d89c72  archive::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, archive::ParserOptions const&) + 146
5  0x10e3b3c72  archive::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, archive::ParserOptions const&) + 146
6  0x105db4c8e  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 2734
6  0x10e3dec8e  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 2734
7  0x105db7fa0  ___ZN2ld4tool10InputFilesC2ER7Options_block_invoke + 48
8  0x7ff80acd7a77  _dispatch_client_callout2 + 8
7  0x10e3e1fa0  ___ZN2ld4tool10InputFilesC2ER7Options_block_invoke + 48
9  0x7ff80ace94e1  _dispatch_apply_invoke + 213
8  0x7ff80acd7a77  _dispatch_client_callout2 + 8
9  0x7ff80ace94e1  _dispatch_apply_invoke + 213
10  0x7ff80acd7a44  _dispatch_client_callout + 8
collect2: error: ld returned 1 exit status
10  0x7ff80acd7a44  _dispatch_client_callout + 8
11  0x7ff80ace77f6  _dispatch_root_queue_drain + 683
11  0x7ff80ace77f6  _dispatch_root_queue_drain + 683
12  0x7ff80ace7e4d  _dispatch_worker_thread2 + 160
13  0x7ff80ae53c9d  _pthread_wqthread + 256
12  0x7ff80ace7e4d  _dispatch_worker_thread2 + 160
A linker snapshot was created at:
	/tmp/hhblits-2022-10-24-231407.ld-snapshot
ld: Assertion failed: (_file->_atomsArrayCount == computedAtomCount && "more atoms allocated than expected"), function parse, file macho_relocatable_file.cpp, line 2061.
13  0x7ff80ae53c9d  _pthread_wqthread + 256
A linker snapshot was created at:
	/tmp/hhmake-2022-10-24-231407.ld-snapshot
ld: Assertion failed: (_file->_atomsArrayCount == computedAtomCount && "more atoms allocated than expected"), function parse, file macho_relocatable_file.cpp, line 2061.
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make[2]: *** [src/hhfilter] Error 1
make[1]: *** [src/CMakeFiles/hhfilter.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [src/hhblits] Error 1
make[2]: *** [src/hhmake] Error 1
make[1]: *** [src/CMakeFiles/hhblits.dir/all] Error 2
make[1]: *** [src/CMakeFiles/hhmake.dir/all] Error 2
0  0x105423ffa  __assert_rtn + 139
1  0x10525728d  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 4989
2  0x105247f8f  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 207
3  0x105295404  archive::File<x86_64>::makeObjectFileForMember(archive::File<x86_64>::Entry const*) const + 1268
4  0x105294a8b  archive::File<x86_64>::File(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, archive::ParserOptions const&) + 1035
5  0x105293c72  archive::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, archive::ParserOptions const&) + 146
6  0x1052bec8e  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 2734
7  0x1052c1fa0  ___ZN2ld4tool10InputFilesC2ER7Options_block_invoke + 48
8  0x7ff80acd7a77  _dispatch_client_callout2 + 8
9  0x7ff80ace94e1  _dispatch_apply_invoke + 213
10  0x7ff80acd7a44  _dispatch_client_callout + 8
11  0x7ff80ace77f6  _dispatch_root_queue_drain + 683
12  0x7ff80ace7e4d  _dispatch_worker_thread2 + 160
13  0x7ff80ae53c9d  _pthread_wqthread + 256
A linker snapshot was created at:
	/tmp/hhalign_omp-2022-10-24-231407.ld-snapshot
ld: Assertion failed: (_file->_atomsArrayCount == computedAtomCount && "more atoms allocated than expected"), function parse, file macho_relocatable_file.cpp, line 2061.
collect2: error: ld returned 1 exit status
make[2]: *** [src/hhalign_omp] Error 1
make[1]: *** [src/CMakeFiles/hhalign_omp.dir/all] Error 2
make: *** [all] Error 2

## Context
Providing context helps us come up with a solution and improve our documentation for the future.
Compiling hh-suite for MPI support 
## Your Environment
Include as many relevant details about the environment you experienced the issue in.
* Version/Git commit used: 
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
* Operating system and version: iOS 13.0 Ventura

**Comment by milot-mirdita** [comment]
Do you mean macOS? Make sure you have the latest Xcode beta installed, that should fix the issue.

**Comment by milot-mirdita** [comment]
See: https://github.com/Homebrew/discussions/discussions/3659

**Comment by ndmaduro** [comment]
Yeah, I meant MacOS 13.0 Ventura. Apologies.

After installing XCode 14.1 RC2, the issue is now resolved. Thank you for the help!

**Comment by ndmaduro** [comment]
Yeah, I meant MacOS 13.0 Ventura. Apologies.

After installing XCode 14.1 RC2, the issue is now resolved. Thank you for the help!
