### ISSUE TITLE
Initial ppc64le code available for review/comments.

### ISSUE THREAD

**Issue by sowani** [soedinglab/hh-suite#34]
Hi,

With the generous help of hh-suite community and Power8 community, I am done with the first phase of porting hh-suite to Power8 platform.

hh-suite code ported to ppc64le is available for review at https://github.com/asowani/hh-suite/tree/hpc for those who are curious/interested/willing to help. This code is at a very primitive level and I can't even call it "beta" - it is even below that. Also this code is not fully functional yet.

If you happen to check this code and find any issues, I am very eager and would be very happy to know your comments/corrections/suggestions/feedback.

Thanks,
Atul.

**Comment by martin-steinegger** [comment]
Congratulations. :) 

Unfourtantly I do not have any power8 computer here to test it.
I just checked your changes briefly. All looks good to me. 
But I just saw one thing that is a bit unintuative.
Why do you include "emmintrin.h" in src/hhblits.h and src/hhhmmsimd.h. 
Wouldn't it be better to do this in the simd.h?

**Comment by sowani** [comment]
Actually I am _excluding_ emmintrin.h file when working on P8. These includes are already there in the original code.

**Comment by sowani** [comment]
I will move the emmintrin.h include to simd.h in addition to P8 changes. Thanks!

**Comment by martin-steinegger** [comment]
Should we merge your forked version to the main branch?

**Comment by sowani** [comment]
@martin-steinegger 
Thanks for the proposal! I don't think it's ready yet for merging with main branch. Looks like I need to do a lot of debugging/fixes before I reach that stage! I will definitely let you know once the code reaches there.

Mit freundlichen Grüßen/Best regards,
Atul.
