### ISSUE TITLE
error running hhblits on costumized database

### ISSUE THREAD

**Issue by idrinnen** [soedinglab/hh-suite#342]
I am running hhblits on a customized database that I built of 5 fasta entries. This is just a test as I want to built a database of an entire proteome. I did not get any error when building the database but when I try to search it using hhblits, I receive this error message:
/bioinfo/local/build/Centos/hhsuite/hhsuite-3.3.0-SSE2/bin/hhblits -cpu 4 -i ../../../ApisCENPA.fa -d five_fasta -o test.hhr -n 1

- 12:05:56.804 INFO: Searching 5 column state sequences.

- 12:05:56.901 INFO: ../../../ApisCENPA.fa is in A2M, A3M or FASTA format

- 12:05:56.902 INFO: Iteration 1

- 12:05:57.093 INFO: Prefiltering database

- 12:05:57.273 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 5

- 12:05:57.273 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 5

- 12:05:57.273 INFO: HMMs passed 2nd prefilter and not found in previous iterations : 5

- 12:05:57.273 INFO: Scoring 5 HMMs using HMM-HMM Viterbi alignment

- 12:05:57.378 INFO: Alternative alignment: 0

- 12:05:57.379 ERROR: In /big/martin/hh-suite/src/hhdatabase.cpp:443: getTemplateHMM:

- 12:05:57.379 ERROR: 	Unrecognized HMM file format in 'NP_001011562.1'.

- 12:05:57.379 ERROR: 	Context:
'

- 12:05:57.379 ERROR: 

- 12:05:57.379 ERROR: '

Anybody has an advice what could have gone wrong here? Thanks!

**Comment by GodPCWANG** [comment]
Do you know how to build"-d five_fasta"
