### ISSUE TITLE
Effective debugging of Prefilter::ungapped_sse_score().

### ISSUE THREAD

**Issue by sowani** [soedinglab/hh-suite#35]
Hi,

This is w.r.t. the hh-suite Power8/LE porting work I am doing. While checking execution on ppc64le I found that first database prefilter is not getting applied as expected. Hence I started debugging this and reached Prefilter::ungapped_sse_score().

To ensure if the ported intrinsics are behaving identically on both platforms, I wrote a small test program which uses all the simd* calls this particular function uses (like simdi_setzero, simdi8_set, simdi_load, simdi_store etc.). Then I built this test program on x86_64 (which uses SSE intrinsics) and ppc64le (uses gcc AltiVec intrisics). The output on both the platforms was identical, so I am assuming everything as far as SSE/AltiVec intrinsics are concerned, is working fine.

Now with this understanding, I came back to ungapped_sse_score() and I still see a difference, The score value at the end of this function is way different on ppc64le (205) than x86_64 (79). Basically, no filter is getting applied.

My suspicion is on the behaviour of the code which loops over db sequence positions and query band positions (the "S" value). Since this loop mainly deals with addresses, they are of no use when comparing across platforms. Is there any optimal way I can ensure that the data fetched from DB is correct?

Thanks,
Atul.

**Comment by martin-steinegger** [comment]
I would reduce your database to just the one entry that fails and print out the score of the x86_64 version and the ppc64le and diff them. 

You can do this by removing all other entries from the ffindex file. 

    grep FAIL_ENTRY_ID YOUDB_cs219.ffindex > YOUDB_cs219.new.ffindex 
    mv YOUDB_cs219.ffindex YOUDB_cs219.old.ffindex
    mv YOUDB_cs219.new.ffindex  YOUDB_cs219.ffindex

**Comment by sowani** [comment]
I'm sorry but it's not clear to me. I am using command "hhblits -i /tmp/hh-results/1.fasta -d /root/hh-suite/dbs/scop70_1.75 -n 1 -oa3m /tmp/hh-results/1.a3m -o /tmp/hh-results/1.hhr -cpu 1" to test. So what should be the "FAIL_ENTRY_ID" vaule? Here's sample output of this command:

- 19:16:46.501 INFO: Searching 13730 column state sequences.
- 19:16:46.601 INFO: /tmp/hh-results/1.fasta is in A2M, A3M or FASTA format
- 19:16:46.601 INFO: Iteration 1
- 19:16:48.914 INFO: Prefiltering database
- 19:16:48.914 INFO: ATUL: before adding pseudocounts, 0
- 19:16:51.219 INFO: ATUL: before prefilter_db
- 19:16:51.219 INFO: ATUL: in HHblitsDatabase::prefilter_db
- 19:16:51.219 INFO: ATUL: in Prefilter::prefilter_db
- 19:16:51.246 INFO: ATUL: num_dbs: 13730
- 19:16:51.246 INFO: ATUL: calling ungapped_sse_score (1)
- 19:16:51.246 INFO: ATUL: in Prefilter::ungapped_sse_score

Thanks!

Mit freundlichen Grüßen,
Atul.

**Comment by martin-steinegger** [comment]
You mentioned a difference in score after the ungapped_see_score stage. My script reduces the database to only one entry. FAIL_ENTRY_ID is the ID of the entry that has the produces the wrong score (205 instead of 79).

**Comment by meiermark** [comment]
Since the power8 port is finished, I assume that this issue can be closed?
