### ISSUE TITLE
c++: fatal error: Killed signal terminated program cc1plus

### ISSUE THREAD

**Issue by YourArka** [soedinglab/hh-suite#360]
- The Error Output

c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[3]: *** [ApplicationUtilities/DefaultClient/src/CMakeFiles/DefaultClient.dir/build.make:95: ApplicationUtilities/DefaultClient/src/CMakeFiles/DefaultClient.dir/DefaultClient.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:16699: ApplicationUtilities/DefaultClient/src/CMakeFiles/DefaultClient.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:16539: SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [Makefile:4211: SampleApp] Error 2

**Hi, recently I have been working on Alexa using Raspberry Pi Zero W, every time I reach 90% the errors pops up (error text shown up ).

Can anyone help me out with this error. I have been struggling on this since 3days**.

Also I'm using the SDK v1.26 because the new SDK v3.0 is not supporting for some reasons.

- link to the web : https://developer.amazon.com/de-DE/docs/alexa/avs-device-sdk-1-2x/raspberry-pi.html

Specs :- 

- Raspberry Pi Zero W. (Both WiFi and Bluetooth Supported)
- 1GHz BCM2835 single-core processor with 512MB RAM.
- Raspbian OS Lite 32 bit.
- Added extended 16gb SD card into it.
- Headless setup.

![image](https://github.com/soedinglab/hh-suite/assets/142826342/8460e50c-79d0-4386-b8f9-1d5acd9ad110)

**Comment by milot-mirdita** [comment]
I don't think you are right here. Please ask the developers AVS for support.
