### ISSUE TITLE
error while loading shared libraries: libHH_OBJECTS.so

### ISSUE THREAD

**Issue by gabrielctn** [soedinglab/hh-suite#361]
:exclamation: Make to check out our [User Guide](https://github.com/soedinglab/hh-suite/wiki).

## Expected Behavior
hhalign and hhblits executables should run normally.

## Current Behavior
```
$ module load hh-suite-3.3.0
$ hhalign
hhalign: error while loading shared libraries: libHH_OBJECTS.so: cannot open shared object file: No such file or directory
$ hhblits
hhblits: error while loading shared libraries: libHH_OBJECTS.so: cannot open shared object file: No such file or directory
```

## Steps to Reproduce (for bugs)
Here is the cmake command generated by Spack using the recipe I modified in the WIP PR https://github.com/spack/spack/pull/40927
`
'/root/admin/scripts/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-9.4.0/cmake-3.27.7-lzkurf7odr74bjnidseabtsgsxws5tma/bin/cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/root/admin/scripts/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-9.4.0/hh-suite-3.3.0-lmgpjzfpf45o4o7sutgjg7u3osnywme4' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/root/admin/scripts/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-9.4.0/hh-suite-3.3.0-lmgpjzfpf45o4o7sutgjg7u3osnywme4/lib;/root/admin/scripts/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-9.4.0/hh-suite-3.3.0-lmgpjzfpf45o4o7sutgjg7u3osnywme4/lib64' '-DCMAKE_PREFIX_PATH:STRING=/root/admin/scripts/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-9.4.0/cmake-3.27.7-lzkurf7odr74bjnidseabtsgsxws5tma;/root/admin/scripts/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-9.4.0/gmake-4.4.1-z4d7mg72biaaudzghw2ul5o5wykhv5np' '-DBUILD_SHARED_LIBS:BOOL=ON' '-DNATIVE_ARCH:BOOL=OFF' '-DCHECK_MPI=0' '-DHAVE_SSE2=1' '/tmp/root/spack-stage/spack-stage-hh-suite-3.3.0-lmgpjzfpf45o4o7sutgjg7u3osnywme4/spack-src'
`

After looking a little bit into it, the library `libHH_OBJECTS.so` is in a `src` directory, the same as hhblits and other executables, but for some reason they are never copied into the installation directory.
Someone knows what to change in order to solve that ?

## HH-suite Output (for bugs)
`error while loading shared libraries: libHH_OBJECTS.so: cannot open shared object file: No such file or directory`

## Context
I try to build HH-Suite on my cluster using Spack. The recipe to build the package was not complete so I am trying to make it work. It works for static builds but some issues still happen when trying to build with shared libraries.

## Your Environment
* Version/Git commit used: 3.3.0
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory): I build for x86_64 cpu which support at least sse2
* Operating system and version: Ubuntu 22.04

**Comment by milot-mirdita** [comment]
Please contact the maintainer of the spack recipe or your cluster admins. We don’t support building any part of our software as shared libraries (.so). You can download precompiled static binaries from mmseqs.com/hhsuite

**Comment by gabrielctn** [comment]
Alright that's what I thought. Thanks for your fast answer !
