### ISSUE TITLE
Link to download hhpred databases is broken

### ISSUE THREAD

**Issue by merkys** [soedinglab/hh-suite#37]
Link to [ftp://toolkit.genzentrum.lmu.de/pub/HH-suite/databases/hhsearch_dbs/](ftp://toolkit.genzentrum.lmu.de/pub/HH-suite/databases/hhsearch_dbs/), which is given in [scripts/hhpred/README](../blob/master/scripts/hhpred/README) to download hhpred databases, is broken.

**Comment by croth1** [comment]
Hi @merkys, thanks for spotting this. We recently switched to a new webserver. The new link is:

 http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsearch_dbs/

**Comment by merkys** [comment]
Thank you @croth1 for such a quick response!

**Comment by altaetran** [comment]
I believe this is broken again.

**Comment by milot-mirdita** [comment]
Hi altaetran

For hhsearch you can use the same databases as hhblits uses at:
http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/

HHpred is currently unsupported. We are currently reworking it and making it able to use mmCIF structures, but this is not ready for prime time yet.

The old unsupported databases are still available here:
http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/old-releases/

**Comment by proteinmechanic** [comment]
Has there been any update on the HHpred front? Or is it still unsupported?
Any links to download the databases from?

**Comment by milot-mirdita** [comment]
Nothing new to report yet. Sorry!

**Comment by proteinmechanic** [comment]
Just to make sure I have the correct understanding of this:

1) HHsuite has a bunch of programs -- hhblits: does sequence alignment -- against databases provided to it.
2) HHpred can use the result of those alignments (or do them itself, given other programs are present) and through the use of modeller make predictions of protein structures.

It is the 2nd part (HHpred) that is causing trouble with missing A3M databases -- so a wok around this would be that we use (for now while you fix this) the results from HHblits -- get possible templates - and then then manually work with those templates to produce alignments and then use Modeller to get protein structures. Does this summarise it? Or is there some essential point that I missed.
