### ISSUE TITLE
Wrong format in printf statement

### ISSUE THREAD

**Issue by tillea** [soedinglab/hh-suite#40]
Hi,

hhblits.cpp uses the %i printf(3) conversion to format a 'double' value ( see [Debian bug tracking system](https://bugs.debian.org/851764) )

To help us debugging your issue, please make sure you

- HHsuite 3.0-beta.2
- [user-guide](https://github.com/soedinglab/hh-suite/blob/master/hhsuite-userguide.pdf) - is affected by this issue
- Patch is included in  [bug report](https://bugs.debian.org/851764)

**Please note besides this**
There are [a lot of patches](https://anonscm.debian.org/cgit/debian-med/hhsuite.git/tree/debian/patches) available in the Debian packaging which should have been propagated by the maintainer before.  I guess this has not happened yet and thus I'm pointing you to this set of patches to enable you cherry-picking from it as far as it applies.
Kind regards, Andreas.

**Comment by meiermark** [comment]
Should be fixed now. I included some patches. However, other patches seem to be debian specific.

**Comment by tillea** [comment]
Hi Markus,

On Thu, Jan 19, 2017 at 05:30:45AM -0800, Markus Meier wrote:
> Should be fixed now. I included some patches. However, other patches seem to be debian specific.

Thanks.  Yes, some patches are Debian specific and should not be
applied.

Thanks for your quick response

      Andreas.

-- 
http://fam-tille.de
