### ISSUE TITLE
Problem building the hh-suite databases

### ISSUE THREAD

**Issue by lukaszimmermann** [soedinglab/hh-suite#43]
Hi everyone,

I encounter problems building the hh-suite databases. Running ffindex_apply_mpi together with hhblits results in the output as contained in the file [have.txt](https://github.com/soedinglab/hh-suite/files/750930/have.txt). I know that the output should look like in 
[should.txt](https://github.com/soedinglab/hh-suite/files/750947/should.txt)

It seems that ffindex_apply_mpi either does not terminate hhblits (the child process) correctly or that hhblits does not produce output on standard out. (The output "iteration 1" is too far ahead in the code of hhblits, so the child process does not terminate). 

I looked into the code and found that the read call
in ffindex_apply_mpi  blocks, so I think this code here is problematic:

  fcntl(pipefd_stdout[0], F_SETFL, flags); // Remove O_NONBLOCK
  ssize_t r;
  while ((r = read(pipefd_stdout[0], b, PIPE_BUF)) > 0) {
                b += r;
  }

If I use the same binaries and databases, the problem may appear on one machine, but not necessarily on the other. The problem appears on all on our cluster nodes, that is why I am unable to create the hh-suite databases. 

Do you have any suggestions about this?  I have not yet tried to use hhblits_mpi. That might also be an option. However, for me there seems to be a bug in ffindex_apply_mpi.

**Comment by meiermark** [comment]
Hello,

could you share your command line?

Cheers,
Markus

**Comment by meiermark** [comment]
@lukaszimmermann: is this issue persisting?

**Comment by lukaszimmermann** [comment]
@meiermark  No, this issue is resolved and the databases can be built successfully. 
As far as I remember, we switched to hhblits_mpi for the databases.

Thanks for asking!

Best wishes
Lukas
