### ISSUE TITLE
Merge hhmakemodel.pl and hhmakemodel.py

### ISSUE THREAD

**Issue by lukaszimmermann** [soedinglab/hh-suite#45]
Hello everybody,

I'd be interested in the necessary steps to merge the files
hhmakemodel.pl
hhmakemodel.py

As far as I know, hhmakemodel.py support mmCIF, while the Perl version does not.
Furthermore, hhmakemodel.py only supports PDBCODE_CHAIN identifiers, while hhmakemodel.pl
can also work with DALI and SCOP identifiers.

I think the Python version should be extended such that the Perl version becomes obsolete.
What do you think? What steps would this encompass?  I'd e interested in working on that.

Best wishes
Lukas

**Comment by croth1** [comment]
Hi Lukas! Thanks for offering your help! Please excuse that responding may take a bit longer than usual, @meiermark is currently not available.

**Comment by meiermark** [comment]
Good question.
If there is a dali or scop identifier you would have to map it to the corresponding PDB entry. 

And you would need a PDB parser in case there are no mmcifs. 

In doubt you have to check if your sequence comes from the PDB or MMcif. 

If you want to adjust this script for pdb's it is probably useful to first adjust the script pdb2fasta.py so it can handle the pdb format in the same way as the MMcif format.

**Comment by meiermark** [comment]
Since the MMcif format shall replace the old pdb format, there is probably no reason to integrate support for the old format.
