### ISSUE TITLE
HHsuite_dbs pfam_30 corrupt?

### ISSUE THREAD

**Issue by jamespjh** [soedinglab/hh-suite#46]
Hi,

pfam_30 seems to be corrupt at http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/
: it is very much smaller than pfam_29 was.

**Comment by meiermark** [comment]
It is corrupt. I will look into it

**Comment by meiermark** [comment]
Should be fine now. There was an error in one of the update scripts.
