### ISSUE TITLE
Issue after updating to pdb70_from_mmcif_15Feb17

### ISSUE THREAD

**Issue by mmabrouk** [soedinglab/hh-suite#47]
Hello,

We tried updating the pdb70 database to the newest version (pdb70_from_mmcif_15Feb17). HHblits (hhsuite 3.0.0) now fails. This is the command we use:

`/scratch/mahmoud/apps/hh-suite/build/bin/hhblits -d /scratch/databases/hhblits/pdb70_latest -p 20 -z 0 -b 0 -i Data/2017-02-11_00000008_1_32/templates/2017-02-11_00000008_1_32.a3m -o Data/2017-02-11_00000008_1_32/templates/2017-02-11_00000008_1_32.hhr
`

This is the error we get:

```

- 11:21:13.860 WARNING: No sequence name preceding following line in 3C1A_A:
'------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------'

- 11:21:13.882 ERROR: Uncharacterized protein OS=Enterobius vermicularis PE=4 SV=1
- 11:21:13.882 ERROR: Error in /scratch/mahmoud/apps/hh-suite/src/hhalignment.cpp:1236: Compress:

- 11:21:13.882 ERROR: 	sequences in 3C1A_A do not all have the same number of columns, 

- 11:21:13.882 ERROR: 	
e.g. first sequence and sequence tr|A0A0N4VN87|A0A0N4VN87_ENTVE.

- 11:21:13.882 ERROR: Check input format for '-M a2m' option and consider using '-M first' or '-M 50'

```
Reverting to the old database version solves the issue.

Here are our system informations:
Version use hhsuite 3.0.0
Centos 6.3 

Thank you for your help!

Yours,
Mahmoud

**Comment by meiermark** [comment]
I am looking into it. Might take some time.

**Comment by meiermark** [comment]
The database was corrupted. The updates scripts were fixed.
The newly published pdb_mmcif databases should work now.
