### ISSUE TITLE
hhfilter 65535 sequence limit

### ISSUE THREAD

**Issue by alquraishi** [soedinglab/hh-suite#51]
It appears that hhfilter has an undocumented limit on the number of sequences it outputs (65535). This should be documented and a clear warning given to the user. I just lost 100,000s of compute hours because of this (filtered very large MSAs and then erased them, only to realize that they were being severely truncated).

**Comment by croth1** [comment]
@alquraishi, you are right, this should definitely be documented. We are very sorry for the inconvenience.

**Comment by mircare** [comment]
I got a similar issue with HHblits. It would be great to pass this threshold sometimes.

**Comment by meiermark** [comment]
Hello,

you are right. There should be a warning. And there was a warning, but it was not reachable in the code. This should be fixed now.

`hhfilter -i huge.a3m -o test.a3m
- 16:35:00.940 INFO: Input file = huge.a3m

- 16:35:00.940 INFO: Output file = test.a3m

- 16:35:01.376 WARNING: Maximum number 65535 of sequences exceeded in file huge.a3m

Done`

In general it is possible to raise this limit if you change the constant `MAXSEQ` in `src/hhdecl.h` and rebuild/install hhsuite:

`const int MAXSEQ=65535; //max number of sequences in input alignment`

**Comment by alquraishi** [comment]
Can this be made an option that is passed through the command-line to hhfilter? Seems like a natural thing to do instead of having to recompile. Similarly for hhblits, etc.

**Comment by meiermark** [comment]
It might be done, but it requires more work. At the moment, there is no developer (PostDoc, PhD or Master/Bachelor student) working on HHblits.

**Comment by alquraishi** [comment]
Are there other limits on how large MAXSEQ can get? I've tried increasing it and recompiling, but I can only get it to about 2,000,000 before `hhfilter` starts segfaulting on start. I'm not sure what the cause is, but I'd like to increase it a lot higher (~100,000,000) .

**Comment by dyl4nm4rsh4ll** [comment]
any update on this? i have just ran into the exact same problem myself

**Comment by anar-rzayev** [comment]
@dylanmontanamarshall I mean, the only option so far seems to just manually increase the MAX_SEQ and re-compile it
