### ISSUE TITLE
IBM-HPC: Enable and optimize HH-Suite for POWER8 VSX SIMD support

### ISSUE THREAD

**Issue by edelsohn** [soedinglab/hh-suite#52]
Enhance HH-Suite to utilize POWER8 VSX SIMD instructions for PPC64LE Linux environment.

**Comment by croth1** [comment]
Unfortunately, we don't have access to PowerPC machines and therefore rely on help from the community for supporting this.

**Comment by edelsohn** [comment]
A bounty was created and a developer already is working on this.

Note that POWER8 VMs are available around the world, including
http://osuosl.org/services/powerdev/ - OSUOSL
http://research.redhat.com/powerlinux-openpower-development-hosting/ - FIT Brno

**Comment by dmiller423** [comment]
Yes,  PR #53 should close this out :)

**Comment by meiermark** [comment]
The builds on travis fail with this pull request... so we can't merge it at the moment.

**Comment by dmiller423** [comment]
Yes,  I should have it taken care of today.

**Comment by meiermark** [comment]
Should be done now. Nice work :)
