### ISSUE TITLE
renumberpdb.pl has a bug to parse pdbfile variable

### ISSUE THREAD

**Issue by zhujianwei31415** [soedinglab/hh-suite#55]
In the script, the operator "." in line 382 should be changed to ".=".
File structure:
    ./
    ./1a3a.pdb
    ./1a3a_A.a3m
Command:
    renumberpdb.pl 1a3a_A.a3m -d ./
Error:
"ERROR in Align.pm: sequence x is empty"

wrong:
`elsif (-e $pdbfile."$pdbcode.pdb")      {$pdbfile."$pdbcode.pdb";}`
right:
`elsif (-e $pdbfile."$pdbcode.pdb")      {$pdbfile.="$pdbcode.pdb";}`

**Comment by meiermark** [comment]
You are right. I fixed it in the recent commit. Thank you for your report.
