### ISSUE TITLE
Compile error - cannot "make" due to problem with ffindex.c

### ISSUE THREAD

**Issue by hbaldwin07** [soedinglab/hh-suite#60]
Hi, I'm trying to compile from source code the latest hhsuite 3.0 but am running into trouble. I can do cmake successfully, however I get error messages regarding Open MP (cannot find). But it still generates the "build" files so I think it is okay.. or at least not relevant to my main issue (?)

After running cmake, then make I get this error: 

```
[  2%] Built target ext
Scanning dependencies of target ffindex
[  3%] Building C object lib/ffindex/src/CMakeFiles/ffindex.dir/ffindex.c.o
/Users/HAB/hh-suite/lib/ffindex/src/ffindex.c:525:3: warning: implicit declaration
      of function 'twalkmisc' is invalid in C99 [-Wimplicit-function-declaration]
  twalkmisc(index->tree_root, action, (void *) index_file);
  ^
/Users/HAB/hh-suite/lib/ffindex/src/ffindex.c:527:3: error: function definition is
      not allowed here
  {
  ^
/Users/HAB/hh-suite/lib/ffindex/src/ffindex.c:543:27: warning: incompatible pointer
      types passing 'void (const void *, const VISIT, const int, void *)' to
      parameter of type 'void (*)(const void *, VISIT, int)'
      [-Wincompatible-pointer-types]
  twalk(index->tree_root, action);
                          ^~~~~~
/usr/include/search.h:59:34: note: passing argument to parameter here
void     twalk(const void *, void (*)(const void *, VISIT, int));
                                    ^
/Users/HAB/hh-suite/lib/ffindex/src/ffindex.c:658:1: error: unknown type name
      'Contact'
Contact GitHub API Training Shop Blog About
^
/Users/HAB/hh-suite/lib/ffindex/src/ffindex.c:658:15: error: expected ';' after top
      level declarator
Contact GitHub API Training Shop Blog About
              ^
              ;
/Users/HAB/hh-suite/lib/ffindex/src/ffindex.c:659:1: error: non-ASCII characters
      are not allowed outside of literals and identifiers
© 2017 GitHub, Inc. Terms Privacy Security Status Help
^~
2 warnings and 4 errors generated.
make[2]: *** [lib/ffindex/src/CMakeFiles/ffindex.dir/ffindex.c.o] Error 1
make[1]: *** [lib/ffindex/src/CMakeFiles/ffindex.dir/all] Error 2
make: *** [all] Error 2
```

Before performing cmake I ran "git pull && git submodule deinit && git submodule init && git submodule update" in the main hhsuite directory. It appeared successful... I got this message 
```
Cloning into '/Users/HAB/hh-suite/lib/ffindex'...
Submodule path 'lib/ffindex': checked out '360e4176ece531be34a94298c808349916d016ac'
```

I am fairly new at C++ compilation/etc so I apologize if I'm missing something super obvious... but any help would be appreciated!!!

**Comment by croth1** [comment]
```
/Users/HAB/hh-suite/lib/ffindex/src/ffindex.c:658:1: error: unknown type name
      'Contact'
Contact GitHub API Training Shop Blog About
^
/Users/HAB/hh-suite/lib/ffindex/src/ffindex.c:658:15: error: expected ';' after top
      level declarator
Contact GitHub API Training Shop Blog Abou
```

These errors look extremely strange - As if some plain text ended up in `ffindex.c`. 

Can you try to rename `/Users/HAB/hh-suite`, then clone hh-suite, fetch submodules and see if the error persists?

**Comment by martin-steinegger** [comment]
Mac users can not compile HH-suite at the moment. This bug has todo with ffindex commit https://github.com/soedinglab/ffindex_soedinglab/commit/360e4176ece531be34a94298c808349916d016ac. @meiermark should we rollback it back?

**Comment by hbaldwin07** [comment]
Thank you for the reformatting and quick reply! I have an update that may or may not be relevant to the issue with the ffindex.c file, but hopefully will help others with my Open MP issue. Running cmake as written in your readme instructions plus the option: "-DCMAKE_CXX_COMPILER=gcc-7" seems to fix it. (Total command line: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr/local/ -DCMAKE_CXX_COMPILER=gcc-7 ..)

Also, regarding the ffindex problem: I realized my initial issue post did not include this other warning that I got while running cmake (and still do even with successful Open MP) 

`CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   ffindex_shared`

**Comment by meiermark** [comment]
the commit that caused the problems with mac clang is now reverted.
does the problem persist?

**Comment by hbaldwin07** [comment]
Unfortunately no... it got a lot further.. but now there's a new issue. Before it stopped at make [ 3% ], this time it got to around [66%] before throwing up warnings. It kept going for a little while but this is the ultimate output / error message: 

```
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [bin/hhblits_mpi] Error 1
make[1]: *** [src/CMakeFiles/hhblits_mpi.dir/all] Error 2
make: *** [all] Error 2
```
The whole output was really long so I've attached a .txt file of it with my command line input / output from cmake to make. 
[cmake-output_6.9.17-1513.txt](https://github.com/soedinglab/hh-suite/files/1065030/cmake-output_6.9.17-1513.txt)

**Comment by hbaldwin07** [comment]
Never mind!! I used a different compiler for cmake command (x86_64-apple-darwin15.6.0-c++7) and it worked! Successful installation, can run hhsearch/etc from my shell. Thank you so much!!

**Comment by lccc1230** [comment]
I encounter the same error with ffindex.c during make:

Error after cmake and make:
->cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=${INSTALL_BASE_DIR} -DCMAKE_CXX_COMPILER=gcc-7 ..
->make
Scanning dependencies of target ffindex
[  1%] Building C object lib/ffindex/src/CMakeFiles/ffindex.dir/ffindex.c.o
/Users/luc/Applications/hh-suite/lib/ffindex/src/ffindex.c:526:3: error: function definition is not allowed here
  {
  ^
/Users/luc/Applications/hh-suite/lib/ffindex/src/ffindex.c:542:27: warning: incompatible pointer types passing 'void
      (const void *, const VISIT, const int, void *)' to parameter of type 'void (*)(const void *, VISIT, int)'
      [-Wincompatible-pointer-types]
  twalk(index->tree_root, action);
                          ^~~~~~
/usr/include/search.h:59:34: note: passing argument to parameter here
void     twalk(const void *, void (*)(const void *, VISIT, int));
                                    ^
1 warning and 1 error generated.
make[2]: *** [lib/ffindex/src/CMakeFiles/ffindex.dir/ffindex.c.o] Error 1
make[1]: *** [lib/ffindex/src/CMakeFiles/ffindex.dir/all] Error 2
make: *** [all] Error 2

I have tried different compliers for cmake command including c++-7, g++-7, gcc-7 and x86_64-apple-darwin17.3.0-c++-7, the same error persists;
my gcc is version 7.3.0, and my cmake is 3.10.2. 

I am building hhsuit for the first time, and I am sorry if I miss something obvious... any help is appreciated!!
