### ISSUE TITLE
ffindex_apply_mpi doesn't exist. 

### ISSUE THREAD

**Issue by akaped** [soedinglab/hh-suite#61]
I'm using the version 3.0.0 of hh-suite.

The hhsuitedb.py script points to ffindex_apply_mpi ; but this binary doesn't exist in the bin folder. Instead exists ffindex_apply. I then modified the code to use ffindex_apply.

line 106

`
  check_call(" ".join(["mpirun", "-np", threads, "ffindex_apply", a3m_base_path+".ffdata", large_a3m_index, "-d", hhm_base_path+".ffdata", "-i", hhm_base_path+".ffindex", "--", "hhmake", "-v", str(0), "-i", "stdin", "-o" ,"stdout"]), shell=True) `

I think you should correct this.

**Comment by milot-mirdita** [comment]
Hi Pietro,

`ffindex_apply_mpi` exists when you have compiled the HH-suite with MPI support. If no MPI libraries and headers are available on your system, then the binaries won't be crated.

`mpirun ffindex_apply` will probably not produce the correct output. Please make sure the MPI libraries and headers are installed on your system and recompile the HH-suite.

Best regards,
Milot

**Comment by akaped** [comment]
Thank you very much. In fact I discovered that in this way I'm generating
another error. I will recompile the hh-suite now that I've installed MPI.
Sorry for the false error.

**Comment by salvoc81** [comment]
Sorry to ask on a closed issue but my problem is very similar.
I get the same error with the difference that I do NOT want to use MPI.
What is the flag that I should pass to cmake, or make to compile without MPI support?

I have tried to modify the CMakeLists but could not figure out how to disable the MPI support.

Thanks a lot in advance.

**Comment by milot-mirdita** [comment]
If MPI is installed on the system, it will create additional binaries that are MPI enabled.
Either you remove MPI from your system, or just ignore the _mpi binaries that are generated.
The HHsuite doesn't currently have a flag to ignore the system MPI environment.

**Comment by salvoc81** [comment]
Thanks a lot Milot.
