### ISSUE TITLE
ERROR: In ~/hh-suite/src/hhdatabase.cpp:35: FFindexDatabase: could not open file 'uniprotdb/_cs219.ffdata'

### ISSUE THREAD

**Issue by yazhinia** [soedinglab/hh-suite#65]
I have installed hh-suite 3.0 version in Linux 64bit system in computer cluster. when I run ffindex_apply_mpi command, I get the error saying that _CS916 file could not be opened though all the files are there in the directory (which mentioned in -d option). I suspect it to be export path problem. However I have followed procedure exactly what has given in the user_guide for hhlib path set. I wonder where the source of errors could be?

Example: mpirun -np 10 ffindex_apply_mpi test_fas.ff{data,index} -i test_a3m_wo_ss.ffindex -d test_a3m_wo_ss.ffdata -- hhblits -d ~/hh-suite/build -i stdin -oa3m stdout -n 2

- 17:54:37.260 INFO: Search results will be written to stdin.hhr
- 17:54:37.260 ERROR: In ~/hh-suite/src/hhdatabase.cpp:35: FFindexDatabase:
- 17:54:37.260 ERROR: 	could not open file '~/hh-suite/build_cs219.ffdata'

**Comment by milot-mirdita** [comment]
Could you please execute:

```
head -n 10 ~/hh-suite/build_{a3m,hhm}.ff{data,index} ~/hh-suite/build_cs219.ffindex
ls -lah ~/hh-suite/build_{a3m,hhm,cs219}.ff{data,index}
```

And attach the output here.

**Comment by yazhinia** [comment]
[issue_doc.txt](https://github.com/soedinglab/hh-suite/files/1135460/issue_doc.txt)

**Comment by yazhinia** [comment]
[issue_doc.txt](https://github.com/soedinglab/hh-suite/files/1135463/issue_doc.txt)

**Comment by milot-mirdita** [comment]
Does the error persist, if you call hhblits like this?

mpirun -np 10 ffindex_apply_mpi test_fas.ff{data,index} -i test_a3m_wo_ss.ffindex -d test_a3m_wo_ss.ffdata -- hhblits -d ~/hh-suite/uniprot20_2016_02 -i stdin -oa3m stdout -n 2

**Comment by yazhinia** [comment]
Oh no. Now it is working. I don't know what magic happened. But I am still wonder why that error occurred previously. 

Thank you.

**Comment by milot-mirdita** [comment]
Glad its working now!
