### ISSUE TITLE
Degenerated viterbi alignments

### ISSUE THREAD

**Issue by meiermark** [soedinglab/hh-suite#66]
Hello,

When running hhsearch with the following parameters it ends with a segmentation fault:
`hhsearch -i 8221280.reduced.a3m -d pdb70 -o out.hhr -glob -norealign`

Those parameters are used in the the toolkit in Tuebingen.

We see the following output:
```
13 4CAY_A HISTONE H2A.Z, HISTONE   99.3   4E-15 7.4E-20  107.9   0.0    1  126-126   112-112 (111)
14 4CAY_A HISTONE H2A.Z, HISTONE   99.3 4.6E-15 8.4E-20  107.6   0.1    1  126-126   112-112 (111)
```

Those degenerated alignments caused in previous debugging sessions a segmentation fault:
- Either the alignment is simply so bad (unlikely due to the evalue) and should be filtered out before other methods cause the segmentation fault.
- There might be still a bug in the simd viterbi version. (unlikely)
- Or there is a bug in the backtracing of the viterbi.
Usually the alignments of the viterbi are redone with the Maximum Accuracy alignment algorithm, therefore this bug does not appear in hhsearch/hhblits with default parameters.

Since the bug seems to be caused by the Viterbi.
Could you please handle it, @martin-steinegger ?

**Comment by ostrokach** [comment]
I'm also facing this bug in `HHsearch 3.0.3 (14-07-2017)`.

**Comment by aschafu** [comment]
This might also be related to the empty alignments I see (because in the list of results they are listed as 1 residue long) -- see https://github.com/soedinglab/hh-suite/issues/83

**Comment by martin-steinegger** [comment]
I have pushed a fix for this issue. The hhsuite2.0.16 version removed too short realigned hits from the hit list. We removed this filter in hhsuite3.0, I have added the filter again. See commit https://github.com/soedinglab/hh-suite/commit/4f9699c01f87027a758e70528cafe56fadcb7f80
