### ISSUE TITLE
cmake doesn't process SSE options correctly 

### ISSUE THREAD

**Issue by aschafu** [soedinglab/hh-suite#70]
When trying to compile hhblits, we ran into problems with the SSE flags.
Our machines don't have SSE3, which according to your CHANGES file, shouldn't be a problem.

However, the automatic test finds they do:
`-- Performing Test HAVE_SSE3_EXTENSIONS - Success
`

But then, due to line 29 in src/CMakeLists.txt cmake fails: 
`message( FATAL_ERROR "SSSE3 is needed to run compile! CMake will exit." )
`

We found a workaround to still compile:
-  change line 29 in src/CMakeLists.txt to 
`ADD_DEFINITIONS("-DSSE")
`
- run cmake with additional option  "-DHAVE_SSE3_EXTENSIONS=0"

But you might want to fix the logic in the cmake.

(We are working on current git clone (v3.0-beta.3-5-g79f98ae) 
on Linux  3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux
-- cudos to Tim for working out the work around)

**Comment by milot-mirdita** [comment]
Hi Andrea,

You are right, we are not using SSE3 or SSSE3 instructions. I dropped the requirements down to SSE2.

Could you please retry with the latest git commit? I don't have any CPU available without SSE3 or SSSE3.

Out of curiosity, what CPUs are you using?

Best regards,
Milot

**Comment by aschafu** [comment]
Hi Milot,

wow, that was quick. Yes, the code compiles now as specified in the docs. 

 Thanks!
     Andrea

P.S. As for the CPU, I guess you still know our old Rostlab cluster... 
Here is what jobtest tells about itself:
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 8
model name      : Six-Core AMD Opteron(tm) Processor 2431
stepping        : 0
cpu MHz         : 2393.987
cache size      : 512 KB
