### ISSUE TITLE
Need help with obtaining dsspcmbi binary

### ISSUE THREAD

**Issue by tamuanand** [soedinglab/hh-suite#72]
Hi

I am using HH Suite  2.0.15 and would like to build my custom database.

In this regard, could someone tell me where I can obtain the dsspcmbi binary (as required in HHPaths.pm)

our $dssp    =  "/cluster/databases/dssp/bin/dsspcmbi";  # where is the dssp binary? Used in addss.pl

Thanks in advance,
Anand

**Comment by milot-mirdita** [comment]
Hi Anand,

We do not support HH-suite 2 anymore. With that said you can download the dssp binary from ftp://ftp.cmbi.ru.nl/pub/software/dssp/

The last time I used dssp in conjunction with the HH-suite, I used the dssp-2.0.4-linux-amd64 binary. No idea if newer versions are compatible.

Best regards,

Milot

**Comment by tamuanand** [comment]
Hi Milot,

Thanks for your reply.

You mention that HH-suite 2 is not supported anymore - could you point me to where I can get the latest stable version.  The different versions on this page say "beta" -  https://github.com/soedinglab/hh-suite/releases

Hence, I  got this from http://wwwuser.gwdg.de/~compbiol/data/hhsuite/releases/hhsuite-latest-linux-x86_64.tar.gz 

Thanks,
Anand

**Comment by milot-mirdita** [comment]
Hi Anand,

HH-suite 3 we will remove the beta tag once we finish and submit the manuscript. It is however feature complete.

Please either use the latest github commit. Or the latest github release. We fixed a few minor issues between the last github release and the newest commit.

Best regards,
Milot
