### ISSUE TITLE
Make install error: cannot copy hhsuite-userguide.pdf

### ISSUE THREAD

**Issue by mauricirl** [soedinglab/hh-suite#74]
Hi,
I got the below error during make install
while compiling hhsuite from source (last git commit).

[ 95%] Built target a3m_database_filter
[ 97%] Built target a3m_reduce
[100%] Built target a3m_database_extract
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /./hhsuite-userguide.pdf
CMake Error at cmake_install.cmake:36 (file):
  file INSTALL cannot copy file
  "/home/maurizio/hhsuite/hhsuite-userguide.pdf" to
  "/./hhsuite-userguide.pdf".

Makefile:148: recipe for target 'install' failed
make: *** [install] Error 1

OS: Ubuntu 16.04 LTS
C compiler is GNU 5.4.0
install dir /home/maurizio/hhsuite

Please help to fix this error.

**Comment by croth1** [comment]
Hi @mauricirl,

this problem occurs when the variable `INSTALL_BASE_DIR` is undefined when calling `cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_BASE_DIR} ..`

Can you check if `INSTALL_BASE_DIR` is set to a path you have write access to.

**Comment by mauricirl** [comment]
Fixed. It was a bash syntax problem of INSTALL_BASE_DIR within the braces I still do not undestand but  I manage to work around by typing
maurizio@maurizio:build
$ INSTALL_BASE_DIR=/home/maurizio/hhsuite

and then:
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=${INSTALL_BASE_DIR} ..

Thanks for the support.

**Comment by vinhbiochem** [comment]
Hi @mauricirl and all,

Sorry I'm a bit confused. I'm currently having the trouble that you had a few years back. Where did you happen to write "$ INSTALL_BASE_DIR=/home/maurizio/hhsuite"? Was it in your .bashrc file?

**Comment by croth1** [comment]
@vinhbiochem, `INSTALL_BASE_DIR` is a shell variable which is set in the same shell that you are planning to use for the `cmake` call.

Setting variables is generally done by writing `<VARIABLE_NAME>=<PATH>`  directly in your shell.

In this case `<VARIABLE_NAME>` is `INSTALL_BASE_DIR` and `<PATH>` is `/home/maurizio/hhsuite`, you will have to modify this PATH so that it is a folder on your computer you can write to.

Hope that helps.

**Comment by vinhbiochem** [comment]
Hi @croth1 ,

Thank you for the reply. I messed up big time because I didn't put my path in quotes when setting the install directory. Forgive me if this information was readily available.
