### ISSUE TITLE
Update links to databases in README

### ISSUE THREAD

**Issue by croth1** [soedinglab/hh-suite#75]
From https://github.com/soedinglab/hh-suite/commit/c3567c8b8270ae89584f43d038b2bb40946002d7#commitcomment-25435936

> Can we please get an updated README?
>
>The current link to download pdb70 doesn't work.
>
>If accessing http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/ there >are no pdb70*.a3m.tar.gz, pdb70*.hhm.tar.gz, pdb70*.a3m.tar.gz
>
>Thanks in advance!

cc: @ppflrs

**Comment by kad-ecoli** [comment]
I have the same question. To run hhpred.pl we additionally need the pdb files, which I cannot find within the new pdb70_from_mmcif database files. On the other hand, the old pdb70 database files seems to be stop updating after last April.

**Comment by croth1** [comment]
ping @milot-mirdita

**Comment by milot-mirdita** [comment]
We have updated the database paths in the [wiki](https://github.com/soedinglab/hh-suite/wiki).

HHpred is currently unsupported and will remain so for the foreseeable future, since our request for funding for the HH-suite was denied. Sorry about that.

Uniclust will get a better download links with the next release. See https://github.com/soedinglab/uniclust-pipeline/issues/9

**Comment by gnmcsbnfrmtcsclb** [comment]
From which links can pdb70.a3m.tar.gz, and pdb70.hhm.tar.gz be downloaded? Thanks!

**Comment by martin-steinegger** [comment]
The a3m and hhm are in the pdb70_from_mmcif_latest.tar.gz file on our web server  http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/

**Comment by gnmcsbnfrmtcsclb** [comment]
Thanks! 
The listing now reads after gunzip and tar step as follows:
md5sum
pdb70_a3m.ffdata
pdb70_a3m.ffindex
pdb70_hhm.ffdata
pdb70_hhm.ffindex
pdb70_cs219.ffdata
pdb70_cs219.ffindex
pdb70.cs219
pdb70.cs219.sizes
pdb70_a3m_db.index
pdb70_hhm_db.index
pdb70_a3m_db
pdb70_hhm_db
pdb_filter.dat
pdb70_clu.tsv
Do I now have all the files for running HHPRED in the PDB70 folder?

**Comment by martin-steinegger** [comment]
I do not have the knowledge how to setup HHpred. There is a working hhpred instance at the Toolkit in Tuebingen https://toolkit.tuebingen.mpg.de/#/tools/hhpred

**Comment by gnmcsbnfrmtcsclb** [comment]
Thank you Martin, but I need need something for command line implementation due to number of inputs to analyze. 
Is there anyone other than Johannes himself who you think would be in a position to answer where the elusive a3m file and hhm file for PDB70 are? :)
