### ISSUE TITLE
Accession and permissions to databases

### ISSUE THREAD

**Issue by mauricirl** [soedinglab/hh-suite#76]
Hi, why access to databases, having ownership and being user, needs sudo? I would rather
avoid to use sudo for hhblits.
For example:

maurizio@maurizio:HHsuiteDbs
$ ls -al uniprot20_2016_02/uniprot20_2016_02_a3m_db.index
ls: cannot access 'uniprot20_2016_02/uniprot20_2016_02_a3m_db.index': Permission denied
maurizio@maurizio:HHsuiteDbs
$ sudo ls -al uniprot20_2016_02/uniprot20_2016_02_a3m_db.index
[sudo] password for maurizio: 
-rwxrw-rw- 1 maurizio maurizio 232056270 Feb 26  2016 uniprot20_2016_02/uniprot20_2016_02_a3m_db.index
maurizio@maurizio:HHsuiteDbs
$ sudo head  uniprot20_2016_02/uniprot20_2016_02_a3m_db.index
A0A009DWA6.a3m	2153348524	499
A0A009DWB1.a3m	314353686	2731
A0A009DWB5.a3m	2660763498	537
A0A009DWC0.a3m	2710023866	577
A0A009DWC5.a3m	462983162	397
A0A009DWD0.a3m	2792589419	531
A0A009DWD5.a3m	186677181	371
A0A009DWE5.a3m	3529727842	567
A0A009DWJ5.a3m	354548185	381
A0A009DWL5.a3m	314356417	4132

Thanks for helping.

**Comment by milot-mirdita** [comment]
Your issue looks very puzzling, I just tried to reproduce it. No admin access needed. How did you download and extract the database archive?

Also please consider using the Uniclust30 database for hh-suite:
http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/uniclust-latest

It is the successors of the Uniprot20 and regularly updated.

**Comment by ahcm** [comment]
Your directory permissions are the problem.
```
sudo chmod a+rx uniprot20_2016_02
```

**Comment by mauricirl** [comment]
OK. Thanks.
