### ISSUE TITLE
scripts/hhblitsdb.pl missing in hhblits 3

### ISSUE THREAD

**Issue by kad-ecoli** [soedinglab/hh-suite#78]
I am using hhblits 3.0 on x86_64 Linux. I found that the script "hhblitsdb.pl" previously available under the scripts/ folder in hhblits 2.0.15 is missing in the 3.x version. Is it replaced by a new script? Where can I find it in the new version?

**Comment by milot-mirdita** [comment]
The `hhbsuite.py` script is the successor to that script. However another user currently has trouble with it (#77) and I didn't have time to investigate whats wrong with it yet.
