### ISSUE TITLE
hhsuite 1.x

### ISSUE THREAD

**Issue by kad-ecoli** [soedinglab/hh-suite#79]
I understand you no longer support releases earlier than hhsuite2.x. Yet, we have a project that strangely depends on the old hhsuite 1.5, and wonder whether it is still possible to download the source code for this ancient release.

**Comment by ahcm** [comment]
Maybe you mean hhsearch 1.5?

**Comment by kad-ecoli** [comment]
yes, I do.

**Comment by ahcm** [comment]
Think there was never a source release of hhsearch.
The binaries can be found here:
ftp://ftp.tuebingen.mpg.de/pub/protevo/HHsearch/HHsearch1.5.01/

**Comment by kad-ecoli** [comment]
Yes, that is exactly what we need. Thank you.
