### ISSUE TITLE
Compile error - cannot "make" due to problem with ffindex.c #60 (build error)

### ISSUE THREAD

**Issue by lccc1230** [soedinglab/hh-suite#82]
I am also using a Mac OS

I encounter the same error with ffindex.c during make: see also: https://github.com/soedinglab/hh-suite/issues/60, but the reply in this issue did not solve my error.

Error after cmake and make:
->cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=${INSTALL_BASE_DIR} -DCMAKE_CXX_COMPILER=gcc-7 ..
->make
Scanning dependencies of target ffindex
[ 1%] Building C object lib/ffindex/src/CMakeFiles/ffindex.dir/ffindex.c.o
/Users/luc/Applications/hh-suite/lib/ffindex/src/ffindex.c:526:3: error: function definition is not allowed here
{
^
/Users/luc/Applications/hh-suite/lib/ffindex/src/ffindex.c:542:27: warning: incompatible pointer types passing 'void
(const void *, const VISIT, const int, void )' to parameter of type 'void ()(const void *, VISIT, int)'
[-Wincompatible-pointer-types]
twalk(index->tree_root, action);
^~~~~~
/usr/include/search.h:59:34: note: passing argument to parameter here
void twalk(const void , void ()(const void *, VISIT, int));
^
1 warning and 1 error generated.
make[2]: *** [lib/ffindex/src/CMakeFiles/ffindex.dir/ffindex.c.o] Error 1
make[1]: *** [lib/ffindex/src/CMakeFiles/ffindex.dir/all] Error 2
make: *** [all] Error 2

I have tried different compliers for cmake command including c++-7, g++-7, gcc-7 and x86_64-apple-darwin17.3.0-c++-7, the same error persists;
my gcc is version 7.3.0, and my cmake is 3.10.2.

I am building hhsuit for the first time, and I am sorry if I miss something obvious... any help is appreciated!!

**Comment by martin-steinegger** [comment]
Could you try to checkout the whole repository again and compile it again. We reverted back to the old ffindex version. Does this work for you?

**Comment by lccc1230** [comment]
Hi Martin,

Unfortunately, this didn't work for me and the same error appeared.

However, after I commented line 525 to 541 in ffindex.c, the make miraculously worked and finished without an error. And now I am starting to use hhblits. I am not sure if this action would result in any other problems.

**Comment by milot-mirdita** [comment]
Should be fixed in latest release.
