### ISSUE TITLE
empty alignments on self-made database

### ISSUE THREAD

**Issue by aschafu** [soedinglab/hh-suite#83]
Using hhblits on our self-made pdb_full database (https://s3.eu-central-1.amazonaws.com/pssh3cache/hhblits_dbs/pdb_full.tgz), we see some weird alignments with no aligned residues and high E-values:

No Hit                             Prob E-value P-value  Score    SS Cols Query HMM  Template HMM
  1 a8418e56a71d780ab7da95b75e6d0e  99.7 2.9E-21 2.5E-25  224.4   0.0    1  104-104   131-131 (1056)
  2 2de482719c37194e176357184f1188  99.7   5E-21 4.4E-25  221.8   0.0    1  124-124    38-38  (1028)
  3 a8418e56a71d780ab7da95b75e6d0e  99.6 5.5E-21 4.8E-25  222.0   0.0    1  107-107    29-29  (1056)
  4 a8418e56a71d780ab7da95b75e6d0e  99.6 5.6E-21 4.8E-25  221.9   0.0    1  542-542   488-488 (1056)

Accordingly, the details of the alignment are empty:
No 1
>a8418e56a71d780ab7da95b75e6d0e93
Probab=99.66  E-value=2.9e-21  Score=224.38  Aligned_cols=1  Identities=0%  Similarity=0.000  Sum_probs=0.0  Template_Neff=7.500

No 2
>2de482719c37194e176357184f1188be
Probab=99.65  E-value=5e-21  Score=221.77  Aligned_cols=1  Identities=0%  Similarity=0.000  Sum_probs=0.0  Template_Neff=7.500

Has anyone else seen anything similar?

**Comment by martin-steinegger** [comment]
Do you have a query/target sequence me to reproduce the bug?

**Comment by aschafu** [comment]
Sorry for not having replied earlier. I must have overlooked your question. Here is how to access some example data:

The latest database I have been using is at https://s3.eu-central-1.amazonaws.com/pssh3cache/hhblits_db_creation/pdb_full/201806/pdb_full_201806.tgz and I made a publicly readable folder with an example sequence and the result files I got:
- input sequence: https://s3.eu-central-1.amazonaws.com/pssh3cache/temp/HHblitsDebugging/query.fasta
- hmm created from this (with uniclust30): https://s3.eu-central-1.amazonaws.com/pssh3cache/temp/HHblitsDebugging/query.uniprot20.hhm
- result of running against custom database: https://s3.eu-central-1.amazonaws.com/pssh3cache/temp/HHblitsDebugging/query.uniprot20.pdb.full.hhr

Hope this helps.

**Comment by martin-steinegger** [comment]
I have pushed a fix for this issue. The hhsuite2.0.16 version removed too short realigned hits from the hit list. We removed this filter in hhsuite3.0, I have added the filter again. See commit [4f9699c](https://github.com/soedinglab/hh-suite/commit/4f9699c01f87027a758e70528cafe56fadcb7f80)
