### ISSUE TITLE
NCBI Conserved Domains Database?

### ISSUE THREAD

**Issue by mtisza1** [soedinglab/hh-suite#84]
Hi,

I've used the HHpred server online for some time, but I'm trying to switch to HH-suite on the command line. It's working fine with the databases available at http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/
However, the NCBI CDD (Conserved Domains Database), which is used on HHPRED doesn't appear to be available at the aforementioned ftp site or other sites, as far as I can tell. 
The database available at the NCBI CDD site doesn't have the correct format, and it doesn't appear to be straightforward to convert to the hh-suite-compatible format: ftp://ftp.ncbi.nih.gov/pub/mmdb/cdd

I apologize if I'm just missing something, but if it's truly missing from the collection of databases, would it be possible to make it available along with the other databases? 

Thanks in advance for any help, and thanks for making such a great software package!

Mike

**Comment by martin-steinegger** [comment]
@mtisza1 we do not have the resources to provide the CDDs database as hhsuite compatible format. However it should be possible to create the database with https://github.com/soedinglab/hh-suite/blob/master/scripts/hhsuitedb.py
