### ISSUE TITLE
IBM-HPC: does not build on Power8 with GCC due to vector unit checking and instrinsics

### ISSUE THREAD

**Issue by brockpalen** [soedinglab/hh-suite#9]
We are trying to build hh-suite on Power8.  Our configuration looks like:

```
git clone https://github.com/soedinglab/hh-suite.git
cd hh-suite
git submodule init
git submodule update
mkdir build && cd build

#requires recent cmake 3.5.1 was used
cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/opt/um-ppc64le/hh-suite ..
```

Appears from the error message that cmake checks for SSSE3 and then the code uses abstracted versions of different vector calls in `src/simd.h`.

We would like to add support for Power 8  VSX when compiling on `ppc64le`.  To do this we are assuming

`cmake/CheckSSEFeatures.cmake`
`src/simd.h`

Both need logic added for the VSX intrinsics.  In the end we want a cmake and build that works on Power8.

```
$ cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/opt/um-ppc64le/hh-suite ..
-- The CXX compiler identification is GNU 4.8.3
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compiler is GNU 
-- Using CPU native flags for SSE optimization:  -march=native
-- Performing Test HAVE_MM_MALLOC
-- Performing Test HAVE_MM_MALLOC - Failed
-- Performing Test HAVE_POSIX_MEMALIGN
-- Performing Test HAVE_POSIX_MEMALIGN - Success
-- Performing Test HAVE_AVX2_EXTENSIONS
-- Performing Test HAVE_AVX2_EXTENSIONS - Failed
-- Performing Test HAVE_AVX_EXTENSIONS
-- Performing Test HAVE_AVX_EXTENSIONS - Failed
-- Performing Test HAVE_SSE4_2_EXTENSIONS
-- Performing Test HAVE_SSE4_2_EXTENSIONS - Failed
-- Performing Test HAVE_SSE4_1_EXTENSIONS
-- Performing Test HAVE_SSE4_1_EXTENSIONS - Failed
-- Performing Test HAVE_SSSE3_EXTENSIONS
-- Performing Test HAVE_SSSE3_EXTENSIONS - Failed
-- Performing Test HAVE_SSE3_EXTENSIONS
-- Performing Test HAVE_SSE3_EXTENSIONS - Failed
-- Performing Test HAVE_SSE2_EXTENSIONS
-- Performing Test HAVE_SSE2_EXTENSIONS - Failed
-- Performing Test HAVE_SSE_EXTENSIONS
-- Performing Test HAVE_SSE_EXTENSIONS - Failed
-- No SSE extensions found
CMake Error at src/CMakeLists.txt:26 (message):
  SSSE3 is needed to run compile! CMake will exit.
```

**Comment by croth1** [comment]
ping @meiermark, @martin-steinegger

**Comment by martin-steinegger** [comment]
As you metioned already correctly you need to alter two files to add the support. You need to check for POWER8 in CheckSSEFeatures.cmake and add all needed compiler flags to the SSE_FLAGS variable. After this you have to add the VSX intrinsics to the simd.h power8 code path. We sadly can't help you with that, since none here has any expertise with POWER.

**Comment by danparrot** [comment]
Got CMake to run to completion. That's good. But, make then chokes. Not so good. The reason is that PowerPC vector intrinsics are not quite 1-to-1 with intel intrinsics. 
Question: Is there a regression test to ensure that changes to codebase meet some minimum correctness?

**Comment by martin-steinegger** [comment]
We dont have regression tests. We normally benchmark our software before we release it. Maybe we can give you our benchmark set and you can run it. Does HHblits produces the sames scores as on an SSE machine?

**Comment by danparrot** [comment]
Any of set of tests that will verify functionality after replacing Intel with PowerPC intrinsics will be sufficient. If you provide instructions on where to obtain and how to run the tests, the changes should be completed in a day or so.

**Comment by martin-steinegger** [comment]
Did you finish the PowerPC implementation? @meiermark can you make the benchmark set and scripts for the fold regonition test available for danparrot?

**Comment by meiermark** [comment]
Sure

**Comment by kWeissenow** [comment]
Do I understand it correctly that 3342110adccb02f87b6c6122b40cd9ef3e0d58b3 essentially discontinued David Miller's ppc64le support? We're trying to build the most recent hh-suite on an IBM AC922, but cmake complains about SSE2 missing. The architecture-specific definitions in src/simd.h are still there, however.

**Comment by milot-mirdita** [comment]
Could you make a new issue please?
We don't have any PPC systems and last time I checked there were no free continuous integration solutions for PPC. I am not sure how to keep the PPC build from not breaking without having a CI system, so I am also not very happy about maintaining PPC support.
