### ISSUE TITLE
HHblits fails on some queries against official PDB70 database

### ISSUE THREAD

**Issue by shaunmk** [soedinglab/hh-suite#94]
We've noticed that HHblits fails on some searches against the official pdb70 databases. The command line is

`hhblits -i $tempdir/$jobid.fasta -n 2 -e 0.001 -d $maindir/data/hhsuite/pdb70 -cpu 4 -o $tempdir/$jobid.hhr > $tempdir/$jobid.pdbhhblog 2>&1`

Two query sequences have produced errors (both targets in the ongoing CASP experiment). One example query is given below, followed by the error message seen:

```
>T0965 NADP reductase, Streptomyces RM 5-8, 334 residues|
MGSSHHHHHHSSGLVPRGSHMEGKKILVTGGTGQVARPVAEALAERNEVWCLGRFGTPGVEKELNDRGITTFHWDMDDPGAAAYEGLPDDFTHVLHSAVRRGEDGDVNAAVEVNSVACGRLMTHCRGAEAFLFVSTGALYKRQTLDHAYTEDDPVDGVADWLPAYPVGKIAAEGAVRAFAQVLNLPTTIARLNIAYGPGGYGGVPMLYFKRMLAGEPIPVPKEGQNWCSLLHTDDLVAHVPRLWEAAATPATLVNWGGDEAVGITDCVRYLEELTGVRARLVPSEVTRETYRFDPTRRREITGPCRVPWREGVRRTLQALHPEHLPSESRHSAV
```

The output is

```
- 17:07:40.011 INFO: Searching 59280 column state sequences.

- 17:07:40.104 INFO: /var/www/tmp/consip/0a277fc714547795.fasta is in A2M, A3M or FASTA format

- 17:07:40.105 INFO: Neutralized His-tag between positions 1 and 19

- 17:07:40.105 INFO: Iteration 1

- 17:07:40.445 INFO: Prefiltering database

- 17:07:41.164 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 2108

- 17:07:41.206 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 1112

- 17:07:41.206 INFO: HMMs passed 2nd prefilter and not found in previous iterations : 1112

- 17:07:41.206 INFO: Scoring 1112 HMMs using HMM-HMM Viterbi alignment

- 17:07:41.338 INFO: Alternative alignment: 0

- 17:07:44.430 INFO: 1112 alignments done

- 17:07:44.435 INFO: Alternative alignment: 1

- 17:07:44.947 INFO: 1014 alignments done

- 17:07:44.949 INFO: Alternative alignment: 2

- 17:07:45.005 INFO: 17 alignments done

- 17:07:45.005 INFO: Alternative alignment: 3

- 17:07:45.120 INFO: Realigning 500 HMM-HMM alignments using Maximum Accuracy algorithm

- 17:07:49.162 ERROR: Opening A3M 5K4U_C failed!
```

With the exception of T0954 and T0965 (latter given above), HHblits has run successfully on the other targets we've run so far in CASP13 (query sequences available from http://predictioncenter.org/casp13/targetlist.cgi), without issues, using the exact same parameters above. We have tried rolling back the pdb70 database by a few releases to no avail.

It seems that the error occurs when a query generates a lot of hits. The only workaround we have successfully used is to reduce the E-value threshold by several orders of magnitude, which also leads to fewer hits (this is undesirable for our use case; we would like to get as many hits as possible within the threshold).

We suspect there is an issue with how the pdb70 databases are being built, as the same search against the much larger uniclust30 database runs fine with `-e 0.001`.

To help us debugging your issue, please make sure you

- [x] included the HHsuite version or commit ID
github commit 6657944bae5aff33aafeef35e86e12b868a0fc9f

- [x] added information about your operating system and compiler (if building from source)
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18) on CentOS 6

- [x] checked the [user-guide](https://github.com/soedinglab/hh-suite/blob/master/hhsuite-userguide.pdf) for available documentation
- [x] ideally also included a minimal example for us to reproduce the issue

**Comment by milot-mirdita** [comment]
The issue should be fixed in https://github.com/soedinglab/hhdatabase_cif70/commit/159e62f8c248bd932651974fb6237c4997977e9f now. 

Every release starting from today (pdb70_from_mmcif_180531.tar.gz) should work fine.

**Comment by shaunmk** [comment]
Thanks - we've just confirmed that T0965 runs as expected. The new database seems to work.
