### ISSUE TITLE
ERROR: In ~/hh-suite/src/hhdatabase.cpp:35: FFindexDatabase: could not open file 'uniprotdb/_cs219.ffdata' #65

### ISSUE THREAD

**Issue by sunwGitHub** [soedinglab/hh-suite#95]
I have installed hhsuite on my linux computer through git clone (the latest version3.0-beta). Then I did as the steps as the page https://github.com/soedinglab/hh-suite said. But when I did the $ hhblits -cpu 4 -i data/query.seq. The error occured.
ERROR: In /home/sunw/programs/hh-suite/hh-suite/src/hhdatabase.cpp:35: FFindexDatabase:
ERROR:   could not open file '/home/sunw/programs/hh-suite/hh-suite/databases/uniprot20_2016_02_cs219.ffdata'

I noticed that someone has mentioned this problem, but he solved it out without any hint.

To help us debugging your issue, please make sure you

- [x] included the HHsuite version or commit ID
- [x] added information about your operating system and compiler (if building from source)
- [x] checked the [user-guide](https://github.com/soedinglab/hh-suite/blob/master/hhsuite-userguide.pdf) for available documentation
- [x] ideally also included a minimal example for us to reproduce the issue

**Comment by martin-steinegger** [comment]
Does this problem still occur? Please provide the full log of your call.

**Comment by milot-mirdita** [comment]
See #106 
You might need to either enable memory overcommitment or use a machine with more RAM.
