### ISSUE TITLE
ffindex_apply_mpi  question - using mpirun with qsub 

### ISSUE THREAD

**Issue by tamuanand** [soedinglab/hh-suite#98]
I am trying to run HHSuite to build a custom database.

I am using a qsub shell script to run ffindex_apply_mpi on a hpc cluster in combination with using mpirun (16  nodes, ppn =16 and mpirun –np 256) . However, I find that the mpi threads are not getting distributed on the nodes. Instead, all mpirun jobs get started only on the masternode. 

Please advise.

**Comment by milot-mirdita** [comment]
Do other MPI jobs work on the cluster?
I am not sure I can help you. Your local institute's IT might be able to help. MPI heavily depends on the local configuration.

**Comment by tamuanand** [comment]
I got help from my local IT and got this sorted. Thanks

**Comment by zhaoxvwahaha** [comment]
@tamuanand 
Hi tamuanand，I have the same problem, could you please give me some advice how to solve it?
