### ISSUE TITLE
Problem with hhsuitedb.py (Failed to allocate 9600000064 bytes + SegFault)

### ISSUE THREAD

**Issue by Akusem** [soedinglab/hh-suite#99]
HHSuite version: 90e9a9dd2c (11/05/2018) -> 3.0.3 ?
OS: x86_64 Linux 4.16.13-1-surface

Hello, I'm trying to create a database to be used with hhsearch and I'm encountering error that seem really similar to [issue#62](https://github.com/soedinglab/hh-suite/issues/62).

Like him I have recompile hh-suite after the installation of mpi and setup the path in my zshrc. And I have converted my alignement file from fasta to a3m format using reformat.pl like this :
`reformat.pl fas a3m *.fa .a3m`

After that I have tried to use those file to create the database with this command :
`hhsuitedb.py --ia3m *.a3m --cpu 2 -o db --force` using those files : [alignment_file.tar.gz](https://github.com/soedinglab/hh-suite/files/2115308/alignment_file.tar.gz)
and I obtain this error output :
```
Unlinking entries from '/tmp/tmp8elbzwnq/files.dat'
NP_009327.1_ortho.a3m	0	2720	103	0
Failed to allocate 9600000064 bytes
/home/akusem/hh-suite/lib/ffindex/src/ffindex.c:292 ffindex_index_parse: malloc failed: Cannot allocate memory
[surface-pro-4:04600] *** Process received signal ***
[surface-pro-4:04600] Signal: Segmentation fault (11)
[surface-pro-4:04600] Signal code: Address not mapped (1)
[surface-pro-4:04600] Failing at address: 0x38
[surface-pro-4:04600] [ 0] /usr/lib/libpthread.so.0(+0x11a80)[0x7fbc7bfe6a80]
[surface-pro-4:04600] [ 1] ffindex_apply_mpi(ffmerge_splits+0x197)[0x559e1730baf7]
[surface-pro-4:04600] [ 2] ffindex_apply_mpi(main+0x5fb)[0x559e17309ebb]
[surface-pro-4:04600] [ 3] /usr/lib/libc.so.6(__libc_start_main+0xeb)[0x7fbc7bc3c06b]
[surface-pro-4:04600] [ 4] ffindex_apply_mpi(_start+0x2a)[0x559e17309faa]
[surface-pro-4:04600] *** End of error message ***
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node surface-pro-4 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/akusem/hh-suite/scripts/hhsuitedb.py", line 482, in <module>
    main()
  File "/home/akusem/hh-suite/scripts/hhsuitedb.py", line 478, in main
    check_database(options.output_basename, options.nr_cores, options.force_mode)
  File "/home/akusem/hh-suite/scripts/hhsuitedb.py", line 376, in check_database
    calculate_hhm(threads, output_basename+"_a3m", output_basename+"_hhm")
  File "/home/akusem/hh-suite/scripts/hhsuitedb.py", line 106, in calculate_hhm
    check_call(" ".join(["mpirun", "-np", threads, "ffindex_apply_mpi", a3m_base_path+".ffdata", large_a3m_index, "-d", hhm_base_path+".ffdata", "-i", hhm_base_path+".ffindex", "--", "hhmake", "-v", str(0), "-i", "stdin", "-o" ,"stdout"]), shell=True)
  File "/home/akusem/miniconda3/envs/remotf/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mpirun -np 2 ffindex_apply_mpi db_a3m.ffdata /tmp/tmphp43is_n/large.ffindex -d db_hhm.ffdata -i db_hhm.ffindex -- hhmake -v 0 -i stdin -o stdout' returned non-zero exit status 139.
```
You can see that I have the same error `Failed to allocate 9600000064 bytes` that was presumely fixed in issue 62. The Segmentation Fault and the exit code 139 from the same exact line of code are present too. I thought that it could be because I didn't use the last version of hhsuite but I've reinstall it by built it from source after doing a git clone (I'm on the commit 90e9a9dd2c published in May 2018). I precise I had done an `git submodule init && git submodule update`

I'm on Manjaro i3 17.1.10 Hakoila, my compiler (gcc) version is 8.1.1 and mpirun is on 3.1.0 (Open MPI).

**Comment by milot-mirdita** [comment]
You can get around the issue, by updating the ffindex subrepository to the latest commit on the master branch.

```
cd hh-suite
cd lib/ffindex && git pull origin master && git checkout master && cd -
```

Afterwards run cmake and make again. However the latest ffindex commit is currently not working with the clang compiler, GCC works fine.

**Comment by milot-mirdita** [comment]
This should not happen anymore on the latest release.
